cba.gov.ar,"HTTPSConnectionPool(host='cba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168c558fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168c0bc5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cbn.gov.ng,"HTTPSConnectionPool(host='cbn.gov.ng', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168bd42d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cbn.gov.ng', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168cccdcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cbr.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cbz.si,"HTTPSConnectionPool(host='cbz.si', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cbz.si' doesn't match either of '*.zzzs.si', 'zzzs.si', 'popotnik1.zzzs.si'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ccss.sa.cr,"HTTPSConnectionPool(host='ccss.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b092700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ccss.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b9970d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cdon.dk,"HTTPSConnectionPool(host='cdon.dk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.dk', port=80): Read timed out. (read timeout=2)"
cdon.fi,"HTTPSConnectionPool(host='cdon.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.fi', port=80): Read timed out. (read timeout=2)"
cdon.no,"HTTPSConnectionPool(host='cdon.no', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.no', port=80): Read timed out. (read timeout=2)"
cdon.se,"HTTPSConnectionPool(host='cdon.se', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.se', port=80): Read timed out. (read timeout=2)"
cecdebardage.be,"HTTPSConnectionPool(host='cecdebardage.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168d403730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cecdebardage.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168a7699d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cecile.co.jp,"HTTPSConnectionPool(host='cecile.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cecile.co.jp' doesn't match 'www.cecile.co.jp'"")))","HTTPSConnectionPool(host='www.cecile.co.jp', port=443): Read timed out. (read timeout=2)"
cellphones.com.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
celp.es,"HTTPSConnectionPool(host='celp.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16895d7fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='celp.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168a0ffc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cerimes.fr,"HTTPSConnectionPool(host='cerimes.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1688785340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cerimes.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168a1d4040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cerist.dz,"HTTPSConnectionPool(host='cerist.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168879afa0>, 'Connection to cerist.dz timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cerist.dz', port=80): Read timed out. (read timeout=2)"
cervantes.es,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='cervantes.es', port=80): Read timed out. (read timeout=2)"
ceskaposta.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ceske-hospudky.cz,"HTTPSConnectionPool(host='ceske-hospudky.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ceske-hospudky.cz' doesn't match 'admin.dokempu.cz'"")))","HTTPConnectionPool(host='www.ceske-hospudky.cz', port=80): Read timed out. (read timeout=2)"
cestakbydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cetrogar.com.ar,"HTTPSConnectionPool(host='cetrogar.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cetrogar.com.ar', port=443): Read timed out. (read timeout=2)"
ceylonads.lk,"HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)"
cfaa-antony.fr,"HTTPSConnectionPool(host='cfaa-antony.fr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cfaa-antony.fr', port=80): Read timed out. (read timeout=2)"
cfe.edu.uy,"HTTPSConnectionPool(host='cfe.edu.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168c79a550>, 'Connection to cfe.edu.uy timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cfe.edu.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1687fe1070>, 'Connection to cfe.edu.uy timed out. (connect timeout=2)'))"
cgd.go.th,"HTTPSConnectionPool(host='cgd.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168c11da00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cgd.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1688037d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cgr.go.cr,"HTTPSConnectionPool(host='cgr.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168cd44c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cgr.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1687fe19a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ch10.co.il,"HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)"
chancen.international,"HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)"
chesser.ie,"HTTPSConnectionPool(host='chesser.ie', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chesser.ie', port=80): Read timed out. (read timeout=2)"
chiba.lg.jp,"HTTPSConnectionPool(host='chiba.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168c7ff1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chiba.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168c2a8fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chiquipedia.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
chizumaru.com,"HTTPSConnectionPool(host='chizumaru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168acc06a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chizumaru.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168bbc5dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chooseklaipeda.lt,"HTTPSConnectionPool(host='chooseklaipeda.lt', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chooseklaipeda.lt', port=80): Read timed out. (read timeout=2)"
chordza.blogspot.com,"HTTPSConnectionPool(host='chordza.blogspot.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chordza.blogspot.com', port=80): Read timed out. (read timeout=2)"
chugoku-np.co.jp,"HTTPSConnectionPool(host='chugoku-np.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168cc5cf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chugoku-np.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168d96a9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chutodnaty.sk,"HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)"
cibeg.com,"HTTPSConnectionPool(host='www.cibeg.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cibeg.com', port=443): Read timed out. (read timeout=2)"
ciberforma.pt,"HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)"
ciela.net,"HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cioc.ca,"HTTPSConnectionPool(host='cioc.ca', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16846cab80>, 'Connection to cioc.ca timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cioc.ca', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168baebe50>, 'Connection to cioc.ca timed out. (connect timeout=2)'))"
cipc.co.za,"HTTPSConnectionPool(host='cipc.co.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1684cae550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cipc.co.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16846bff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ciscolinksys.com.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
citc.gov.sa,"HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))","HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))"
city-adm.lviv.ua,"HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
city-map.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city-map.dk,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city.kawasaki.jp,"HTTPSConnectionPool(host='city.kawasaki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16872ee1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.kawasaki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168c11d8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.nagoya.jp,"HTTPSConnectionPool(host='city.nagoya.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1685428e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.nagoya.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16841160a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.saitama.jp,"HTTPSConnectionPool(host='city.saitama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16895faf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.saitama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168c702100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.sapporo.jp,"HTTPSConnectionPool(host='city.sapporo.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1686d2f6d0>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sapporo.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1689611280>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))"
city.sendai.jp,"HTTPSConnectionPool(host='city.sendai.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168b832670>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sendai.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168cf03160>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))"
cityexpress.com,"HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)"
ciu.com.uy,"HTTPSConnectionPool(host='ciu.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b70edc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ciu.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168ad8d910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ciudaddemendoza.gob.ar,"HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)"
civciv.lv,"HTTPConnectionPool(host='www.civciv.lv', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.civciv.lv', port=80): Read timed out. (read timeout=2)"
claro.com.co,"HTTPSConnectionPool(host='claro.com.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f16872e2040>, 'Connection to claro.com.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168d0828e0>, 'Connection to claro.com.co timed out. (connect timeout=2)'))"
claro.com.ec,"HTTPSConnectionPool(host='claro.com.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168b577610>, 'Connection to claro.com.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16847494c0>, 'Connection to claro.com.ec timed out. (connect timeout=2)'))"
claro.com.gt,"HTTPSConnectionPool(host='claro.com.gt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168c1b5070>, 'Connection to claro.com.gt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.gt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168d4bbe80>, 'Connection to claro.com.gt timed out. (connect timeout=2)'))"
claro.com.uy,"HTTPSConnectionPool(host='claro.com.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168ac799a0>, 'Connection to claro.com.uy timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168c53c9d0>, 'Connection to claro.com.uy timed out. (connect timeout=2)'))"
clarochile.cl,"HTTPSConnectionPool(host='clarochile.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168c1b5970>, 'Connection to clarochile.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clarochile.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16843a6370>, 'Connection to clarochile.cl timed out. (connect timeout=2)'))"
clearnotebooks.com,"HTTPSConnectionPool(host='clearnotebooks.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168ab4de20>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clearnotebooks.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168bab87f0>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))"
clevelandclinicabudhabi.ae,"HTTPSConnectionPool(host='clevelandclinicabudhabi.ae', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168af70d30>, 'Connection to clevelandclinicabudhabi.ae timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clevelandclinicabudhabi.ae', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168b441af0>, 'Connection to clevelandclinicabudhabi.ae timed out. (connect timeout=2)'))"
clikisalud.net,"HTTPSConnectionPool(host='clikisalud.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168ba1e910>, 'Connection to clikisalud.net timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clikisalud.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168cc93e80>, 'Connection to clikisalud.net timed out. (connect timeout=2)'))"
cloudnc.fi,"HTTPSConnectionPool(host='cloudnc.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16895d7640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cloudnc.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16857f3130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
club-k.net,"HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)"
clubdam.com,"HTTPSConnectionPool(host='clubdam.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1684728c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='clubdam.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b3b9640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
clubfactory.com,"HTTPSConnectionPool(host='clubfactory.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16841164c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='clubfactory.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b9b84c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
clubmb.ee,"HTTPSConnectionPool(host='clubmb.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clubmb.ee' doesn't match either of 'ns-url-redirect.zoneas.eu', 'www.ns-url-redirect.zoneas.eu'"")))","HTTPSConnectionPool(host='estonia.mercedes-benz-clubs.com', port=443): Read timed out. (read timeout=2)"
cm-oeiras.pt,"HTTPSConnectionPool(host='cm-oeiras.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168de0bb50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cm-oeiras.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16841fffa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cm-porto.pt,"HTTPSConnectionPool(host='cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cmru.ac.th,"HTTPSConnectionPool(host='cmru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b608730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cmru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168d38cd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cmu.ac.th,"HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)"
cmvm.pt,"HTTPSConnectionPool(host='cmvm.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16887855b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cmvm.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16840316d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cnas.ro,"HTTPSConnectionPool(host='cnas.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b832c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cnas.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b858d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cnbctv18.com,"HTTPSConnectionPool(host='www.cnbctv18.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cnbctv18.com', port=443): Read timed out. (read timeout=2)"
cne.go.cr,"HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cnr.gob.sv,"HTTPSConnectionPool(host='cnr.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168a393c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cnr.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1684d6cd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cnrs.fr,"HTTPSConnectionPool(host='cnrs.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168509de20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cnrs.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168cccd2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cnss.ma,"HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))","HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))"
co.ee,"HTTPSConnectionPool(host='co.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168dc015b0>, 'Connection to co.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='co.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168418c400>, 'Connection to co.ee timed out. (connect timeout=2)'))"
cobiss.net,"HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))","HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))"
cocokarafine.co.jp,"HTTPSConnectionPool(host='cocokarafine.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168d94a130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cocokarafine.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1687fcad60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cocolog-nifty.com,"HTTPSConnectionPool(host='cocolog-nifty.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168adab370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cocolog-nifty.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168bd5fe20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
codedfilm.com.ng,"HTTPSConnectionPool(host='codedfilm.com.ng', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='web.codedfilm.com.ng', port=443): Read timed out. (read timeout=2)"
codedwap.com,"HTTPSConnectionPool(host='codedwap.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='codedwapng.com', port=443): Read timed out. (read timeout=2)"
coj.go.th,"HTTPSConnectionPool(host='coj.go.th', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='coj.go.th', port=80): Read timed out. (read timeout=2)"
colciencias.gov.co,"HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
coldiretti.it,"HTTPSConnectionPool(host='coldiretti.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1683f09ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='coldiretti.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b630220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
collegesearch.in,"HTTPSConnectionPool(host='www.collegesearch.in', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.collegesearch.in', port=443): Read timed out. (read timeout=2)"
collider.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
colliers.co.nz,"HTTPSConnectionPool(host='colliers.co.nz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.colliers.co.nz', port=443): Read timed out. (read timeout=2)"
combank.lk,"HTTPSConnectionPool(host='combank.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168cdefe80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='combank.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168a9a9160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
combank.net,"HTTPSConnectionPool(host='combank.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16841d13a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='combank.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168729b4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
commercesuite.com.br,"HTTPSConnectionPool(host='commercesuite.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b608730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='commercesuite.com.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168ddf3940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
company-information.service.gov.uk,"HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))"
compensar.com,"HTTPSConnectionPool(host='compensar.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168c5ea3a0>, 'Connection to compensar.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='compensar.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f168b52a400>, 'Connection to compensar.com timed out. (connect timeout=2)'))"
compraensanjuan.com,"HTTPSConnectionPool(host='compraensanjuan.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b650ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='compraensanjuan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b3b9190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
compumir.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='compumir.ru', port=80): Read timed out. (read timeout=2)"
computerworld.bg,"HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)"
comune.re.it,"HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
comunidadandina.org,"HTTPSConnectionPool(host='comunidadandina.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1684409a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='comunidadandina.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16869252e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
comunidades.net,"HTTPSConnectionPool(host='comunidades.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f168cdce310>, 'Connection to comunidades.net timed out. (connect timeout=2)'))","HTTPConnectionPool(host='comunidades.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1683d0d9a0>, 'Connection to comunidades.net timed out. (connect timeout=2)'))"
conaf.cl,"HTTPSConnectionPool(host='conaf.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16870c5be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='conaf.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1683e5ac10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
confidencial.com.ni,Exceeded 30 redirects.,Exceeded 30 redirects.
congreso.gob.pe,"HTTPSConnectionPool(host='congreso.gob.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168b68c100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='congreso.gob.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168766dbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
conicyt.cl,"HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)"
conjugacion.es,"HTTPSConnectionPool(host='conjugacion.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168ae3a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='conjugacion.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168461c9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
connect.ae,"HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
connectselect.be,"HTTPSConnectionPool(host='connectselect.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f168ac69550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='connectselect.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f168b5573a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
