catdumb.tv,"HTTPSConnectionPool(host='catdumb.tv', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='catdumb.tv', port=80): Read timed out. (read timeout=2)"
cba.gov.ar,"HTTPSConnectionPool(host='cba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0bfe820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0bd2cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cbf.com.br,"HTTPSConnectionPool(host='cbf.com.br', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cbf.com.br', port=80): Read timed out. (read timeout=2)"
cbr.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cbz.si,"HTTPSConnectionPool(host='cbz.si', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cbz.si' doesn't match either of '*.zzzs.si', 'zzzs.si', 'popotnik1.zzzs.si'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cchobby.dk,"HTTPSConnectionPool(host='www.cchobby.dk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cchobby.dk', port=443): Read timed out. (read timeout=2)"
ccss.sa.cr,"HTTPSConnectionPool(host='ccss.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0a97eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ccss.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0b52130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cdon.dk,"HTTPSConnectionPool(host='cdon.dk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.dk', port=80): Read timed out. (read timeout=2)"
cdon.fi,"HTTPSConnectionPool(host='cdon.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.fi', port=80): Read timed out. (read timeout=2)"
cdon.no,"HTTPSConnectionPool(host='cdon.no', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.no', port=80): Read timed out. (read timeout=2)"
cdon.se,"HTTPSConnectionPool(host='cdon.se', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.se', port=80): Read timed out. (read timeout=2)"
cecdebardage.be,"HTTPSConnectionPool(host='cecdebardage.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0b4a520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cecdebardage.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0de4490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cecile.co.jp,"HTTPSConnectionPool(host='cecile.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cecile.co.jp' doesn't match 'www.cecile.co.jp'"")))","HTTPSConnectionPool(host='www.cecile.co.jp', port=443): Read timed out. (read timeout=2)"
ceginformacio.hu,"HTTPSConnectionPool(host='www.ceginformacio.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ceginformacio.hu', port=443): Read timed out. (read timeout=2)"
cellphones.com.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
celp.es,"HTTPSConnectionPool(host='celp.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c097f7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='celp.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0b066d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
centralhospital.com,"HTTPSConnectionPool(host='centralhospital.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c0d8c9a0>, 'Connection to centralhospital.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='centralhospital.com', port=80): Read timed out. (read timeout=2)"
cerimes.fr,"HTTPSConnectionPool(host='cerimes.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0827f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cerimes.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0917af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cervantes.es,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='cervantes.es', port=80): Read timed out. (read timeout=2)"
ceskaposta.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ceske-hospudky.cz,"HTTPSConnectionPool(host='ceske-hospudky.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ceske-hospudky.cz' doesn't match 'admin.dokempu.cz'"")))","HTTPConnectionPool(host='www.ceske-hospudky.cz', port=80): Read timed out. (read timeout=2)"
cestakbydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ceylonads.lk,"HTTPSConnectionPool(host='ceylonads.lk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c07874c0>, 'Connection to ceylonads.lk timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ceylonads.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c081bf40>: Failed to establish a new connection: [Errno 113] No route to host'))"
cfe.edu.uy,"HTTPSConnectionPool(host='cfe.edu.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c07874f0>, 'Connection to cfe.edu.uy timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cfe.edu.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c06e7fd0>, 'Connection to cfe.edu.uy timed out. (connect timeout=2)'))"
cgd.go.th,"HTTPSConnectionPool(host='cgd.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0814790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cgd.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0787370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cgr.go.cr,"HTTPSConnectionPool(host='cgr.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c097f970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cgr.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0a42d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chalmers.se,"HTTPSConnectionPool(host='www.chalmers.se', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.chalmers.se', port=443): Read timed out. (read timeout=2)"
chancen.international,"HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)"
checkmate-cbd.it,Exceeded 30 redirects.,Exceeded 30 redirects.
chiba.lg.jp,"HTTPSConnectionPool(host='chiba.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf7205e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chiba.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf696a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chileestuyo.cl,"HTTPSConnectionPool(host='chileestuyo.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.chileestuyo.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
chiquipedia.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
chizumaru.com,"HTTPSConnectionPool(host='chizumaru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0819670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chizumaru.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf68a940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chordza.blogspot.com,"HTTPSConnectionPool(host='chordza.blogspot.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chordza.blogspot.com', port=80): Read timed out. (read timeout=2)"
chugoku-np.co.jp,"HTTPSConnectionPool(host='chugoku-np.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf671bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='chugoku-np.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf671850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
chutodnaty.sk,"HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)"
ciberforma.pt,"HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)"
cioc.ca,"HTTPSConnectionPool(host='cioc.ca', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bf7205e0>, 'Connection to cioc.ca timed out. (connect timeout=2)'))","HTTPConnectionPool(host='cioc.ca', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0bffbd1c0>, 'Connection to cioc.ca timed out. (connect timeout=2)'))"
cipc.co.za,"HTTPSConnectionPool(host='cipc.co.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0819e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cipc.co.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0975280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cirkwi.com,"HTTPSConnectionPool(host='pro.cirkwi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pro.cirkwi.com', port=443): Read timed out. (read timeout=2)"
ciscolinksys.com.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
citta-forum.nl,"HTTPSConnectionPool(host='citta-forum.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c061a910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='citta-forum.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0bd08e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city-adm.lviv.ua,"HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
city-map.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city-map.dk,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city.kawasaki.jp,"HTTPSConnectionPool(host='city.kawasaki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf6809a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.kawasaki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c08ca700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.nagoya.jp,"HTTPSConnectionPool(host='city.nagoya.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c083b160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.nagoya.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c08ca4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.saitama.jp,"HTTPSConnectionPool(host='city.saitama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0814850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='city.saitama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0afed30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
city.sapporo.jp,"HTTPSConnectionPool(host='city.sapporo.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c09d38b0>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sapporo.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0bf6a38b0>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))"
city.sendai.jp,"HTTPSConnectionPool(host='city.sendai.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bffd67c0>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sendai.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c072ce20>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))"
cityexpress.com,"HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)"
citypark.si,"HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)"
ciu.com.uy,"HTTPSConnectionPool(host='ciu.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c089bbe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ciu.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf6e1070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
civilhetes.net,"HTTPSConnectionPool(host='civilhetes.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='civilhetes.net', port=443): Read timed out. (read timeout=2)"
claro.com.co,"HTTPSConnectionPool(host='claro.com.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c061a4f0>, 'Connection to claro.com.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c08bf370>, 'Connection to claro.com.co timed out. (connect timeout=2)'))"
claro.com.ec,"HTTPSConnectionPool(host='claro.com.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c095dfa0>, 'Connection to claro.com.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c06e7940>, 'Connection to claro.com.ec timed out. (connect timeout=2)'))"
claro.com.gt,"HTTPSConnectionPool(host='claro.com.gt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c0510310>, 'Connection to claro.com.gt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.gt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c09422b0>, 'Connection to claro.com.gt timed out. (connect timeout=2)'))"
claro.com.ni,"HTTPSConnectionPool(host='claro.com.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bfd4f8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPSConnectionPool(host='www.claro.com.ni', port=443): Max retries exceeded with url: /portal/ni/sc/personas/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0730400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
claro.com.uy,"HTTPSConnectionPool(host='claro.com.uy', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c0afe0d0>, 'Connection to claro.com.uy timed out. (connect timeout=2)'))","HTTPConnectionPool(host='claro.com.uy', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c06f27f0>, 'Connection to claro.com.uy timed out. (connect timeout=2)'))"
clarochile.cl,"HTTPSConnectionPool(host='clarochile.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c0720c10>, 'Connection to clarochile.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clarochile.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c09bb820>, 'Connection to clarochile.cl timed out. (connect timeout=2)'))"
clevelandclinicabudhabi.ae,"HTTPSConnectionPool(host='clevelandclinicabudhabi.ae', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bff48310>, 'Connection to clevelandclinicabudhabi.ae timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clevelandclinicabudhabi.ae', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c08141c0>, 'Connection to clevelandclinicabudhabi.ae timed out. (connect timeout=2)'))"
clikisalud.net,"HTTPSConnectionPool(host='clikisalud.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0c06e7f70>, 'Connection to clikisalud.net timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clikisalud.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c066b8e0>, 'Connection to clikisalud.net timed out. (connect timeout=2)'))"
cloudnc.fi,"HTTPSConnectionPool(host='cloudnc.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bffbdee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cloudnc.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0a5a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
clubdam.com,"HTTPSConnectionPool(host='clubdam.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf64d760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='clubdam.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf6f76d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
clubfactory.com,"HTTPSConnectionPool(host='clubfactory.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf696af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='clubfactory.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c095dd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
clubmb.ee,"HTTPSConnectionPool(host='clubmb.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clubmb.ee' doesn't match either of 'ns-url-redirect.zoneas.eu', 'www.ns-url-redirect.zoneas.eu'"")))","HTTPSConnectionPool(host='estonia.mercedes-benz-clubs.com', port=443): Read timed out. (read timeout=2)"
cm-porto.pt,"HTTPSConnectionPool(host='cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cmru.ac.th,"HTTPSConnectionPool(host='cmru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0db87c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cmru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bfd1e5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cmu.ac.th,"HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)"
cmvm.pt,"HTTPSConnectionPool(host='cmvm.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c081b880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cmvm.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0b41cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cne.go.cr,"HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
cnr.gob.sv,"HTTPSConnectionPool(host='cnr.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c09103d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cnr.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c09bb850>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cnss.ma,"HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))","HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))"
cnu.edu.ni,"HTTPSConnectionPool(host='cnu.edu.ni', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPConnectionPool(host='cnu.edu.ni', port=80): Read timed out. (read timeout=2)"
co.ee,"HTTPSConnectionPool(host='co.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bffcb2b0>, 'Connection to co.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='co.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0c0a1e2b0>, 'Connection to co.ee timed out. (connect timeout=2)'))"
cobiss.net,"HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))","HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))"
cocokarafine.co.jp,"HTTPSConnectionPool(host='cocokarafine.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0aa7040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cocokarafine.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0bb1730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cocolog-nifty.com,"HTTPSConnectionPool(host='cocolog-nifty.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c09426a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cocolog-nifty.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bf6f66d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
codedfilm.com.ng,"HTTPSConnectionPool(host='codedfilm.com.ng', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='web.codedfilm.com.ng', port=443): Read timed out. (read timeout=2)"
codedwap.com,"HTTPSConnectionPool(host='codedwap.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='codedwapng.com', port=443): Read timed out. (read timeout=2)"
colciencias.gov.co,"HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
coldiretti.it,"HTTPSConnectionPool(host='coldiretti.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf8a17c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='coldiretti.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bff40a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
collider.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
colliers.co.nz,"HTTPSConnectionPool(host='colliers.co.nz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.colliers.co.nz', port=443): Read timed out. (read timeout=2)"
combank.lk,"HTTPSConnectionPool(host='combank.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0b06520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='combank.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bff40d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
combank.net,"HTTPSConnectionPool(host='combank.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bff8c5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='combank.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0a88d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
commercesuite.com.br,"HTTPSConnectionPool(host='commercesuite.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0975100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='commercesuite.com.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0aacf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
commercialrealestate.com.au,"HTTPSConnectionPool(host='www.commercialrealestate.com.au', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.commercialrealestate.com.au', port=80): Read timed out. (read timeout=2)"
commly.it,Exceeded 30 redirects.,Exceeded 30 redirects.
company-information.service.gov.uk,"HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))"
compensar.com,"HTTPSConnectionPool(host='compensar.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bfd1ec40>, 'Connection to compensar.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='compensar.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0bf6f78b0>, 'Connection to compensar.com timed out. (connect timeout=2)'))"
compraensanjuan.com,"HTTPSConnectionPool(host='compraensanjuan.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0beec0820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='compraensanjuan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c07b6a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
compumir.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='compumir.ru', port=80): Read timed out. (read timeout=2)"
computerworld.bg,"HTTPSConnectionPool(host='computerworld.bg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c001b340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='computerworld.bg', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0a1ec10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
comune.re.it,"HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
comunidadandina.org,"HTTPSConnectionPool(host='comunidadandina.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bd7692e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='comunidadandina.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0a5a7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
comunidades.net,"HTTPSConnectionPool(host='comunidades.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc0bf8cb820>, 'Connection to comunidades.net timed out. (connect timeout=2)'))","HTTPConnectionPool(host='comunidades.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc0bfee5e80>, 'Connection to comunidades.net timed out. (connect timeout=2)'))"
conaf.cl,"HTTPSConnectionPool(host='conaf.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0b34e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='conaf.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0c0924fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
confidencial.com.ni,Exceeded 30 redirects.,Exceeded 30 redirects.
congreso.gob.pe,"HTTPSConnectionPool(host='congreso.gob.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bed9d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='congreso.gob.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bd75d0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
conicyt.cl,"HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)"
conjugacion.es,"HTTPSConnectionPool(host='conjugacion.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0bf834be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='conjugacion.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bd7695b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
connect.ae,"HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
connectselect.be,"HTTPSConnectionPool(host='connectselect.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc0c0a88460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='connectselect.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc0bcd89c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
