cba.gov.ar,"HTTPSConnectionPool(host='cba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c90a2b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c8c7c760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cbn.gov.ng,"HTTPSConnectionPool(host='cbn.gov.ng', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8a4fe20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cbn.gov.ng', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c9d24d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cbr.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
cbz.si,"HTTPSConnectionPool(host='cbz.si', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cbz.si' doesn't match either of '*.zzzs.si', 'zzzs.si', 'popotnik1.zzzs.si'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ccss.sa.cr,"HTTPSConnectionPool(host='ccss.sa.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c7f7b520>, 'Connection to ccss.sa.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ccss.sa.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c8c71d90>, 'Connection to ccss.sa.cr timed out. (connect timeout=2)'))"
cdon.dk,"HTTPSConnectionPool(host='cdon.dk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.dk', port=80): Read timed out. (read timeout=2)"
cdon.fi,"HTTPSConnectionPool(host='cdon.fi', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.fi', port=80): Read timed out. (read timeout=2)"
cdon.no,"HTTPSConnectionPool(host='cdon.no', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.no', port=80): Read timed out. (read timeout=2)"
cdon.se,"HTTPSConnectionPool(host='cdon.se', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='cdon.se', port=80): Read timed out. (read timeout=2)"
cecdebardage.be,"HTTPSConnectionPool(host='cecdebardage.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c9fc3100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='cecdebardage.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c7493b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
cellphones.com.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
celp.es,"HTTPSConnectionPool(host='celp.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c6b64be0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='celp.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c73c01c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cerimes.fr,"HTTPSConnectionPool(host='cerimes.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c6b34d30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cerimes.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c85f11c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cervantes.es,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='cervantes.es', port=80): Read timed out. (read timeout=2)"
ceskaposta.cz,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
ceske-hospudky.cz,"HTTPSConnectionPool(host='ceske-hospudky.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ceske-hospudky.cz' doesn't match 'admin.dokempu.cz'"")))","HTTPConnectionPool(host='www.ceske-hospudky.cz', port=80): Read timed out. (read timeout=2)"
ceskenapady.cz,"HTTPSConnectionPool(host='ceskenapady.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ceskenapady.cz', port=443): Read timed out. (read timeout=2)"
cestakbydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ceylonads.lk,"HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ceylonads.lk', port=443): Read timed out. (read timeout=2)"
cgd.go.th,"HTTPSConnectionPool(host='cgd.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c7622b80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cgd.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c80b8c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ch10.co.il,"HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ch10.co.il', port=443): Read timed out. (read timeout=2)"
chalmers.se,"HTTPSConnectionPool(host='www.chalmers.se', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.chalmers.se', port=443): Read timed out. (read timeout=2)"
chamber.lt,"HTTPSConnectionPool(host='chamber.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chamber.lt', port=443): Read timed out. (read timeout=2)"
chancen.international,"HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chancen.international', port=443): Read timed out. (read timeout=2)"
chiba.lg.jp,"HTTPSConnectionPool(host='chiba.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c84fc0a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chiba.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c9255b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chiesacattolica.it,"HTTPSConnectionPool(host='chiesacattolica.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.chiesacattolica.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
chillpainai.com,"HTTPSConnectionPool(host='chillpainai.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='chillpainai.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
chiquipedia.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
chizumaru.com,"HTTPSConnectionPool(host='chizumaru.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8db0580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chizumaru.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c8b8f160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chooseklaipeda.lt,"HTTPSConnectionPool(host='chooseklaipeda.lt', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='chooseklaipeda.lt', port=80): Read timed out. (read timeout=2)"
chugoku-np.co.jp,"HTTPSConnectionPool(host='chugoku-np.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c61f01c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='chugoku-np.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c7c3f9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
chutodnaty.sk,"HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='chutodnaty.sk', port=443): Read timed out. (read timeout=2)"
cibeg.com,"HTTPSConnectionPool(host='www.cibeg.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cibeg.com', port=443): Read timed out. (read timeout=2)"
ciberforma.pt,"HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciberforma.pt', port=443): Read timed out. (read timeout=2)"
ciela.net,"HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='ciela.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
cinematografo.it,"HTTPSConnectionPool(host='cinematografo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='cinematografo.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
cipc.co.za,"HTTPSConnectionPool(host='cipc.co.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c4d58cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cipc.co.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c981e340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ciscolinksys.com.vn,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
citc.gov.sa,"HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))","HTTPSConnectionPool(host='citc.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citc.gov.sa' doesn't match '*.citc.gov.sa'"")))"
city-adm.lviv.ua,"HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='city-adm.lviv.ua', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
city-map.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city-map.dk,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
city.kawasaki.jp,"HTTPSConnectionPool(host='city.kawasaki.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c83e43a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.kawasaki.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c90e8670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.nagoya.jp,"HTTPSConnectionPool(host='city.nagoya.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c90e8f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.nagoya.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c5de2400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.saitama.jp,"HTTPSConnectionPool(host='city.saitama.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c7396c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='city.saitama.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c3586400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
city.sapporo.jp,"HTTPSConnectionPool(host='city.sapporo.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c9e30520>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sapporo.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c7d9ea90>, 'Connection to city.sapporo.jp timed out. (connect timeout=2)'))"
city.sendai.jp,"HTTPSConnectionPool(host='city.sendai.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c2a49490>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='city.sendai.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c7d84e80>, 'Connection to city.sendai.jp timed out. (connect timeout=2)'))"
cityexpress.com,"HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cityexpress.com', port=443): Read timed out. (read timeout=2)"
citylife.sk,"HTTPSConnectionPool(host='citylife.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'citylife.sk' doesn't match 'www.citylife.sk'"")))","HTTPSConnectionPool(host='www.citylife.sk', port=443): Read timed out. (read timeout=2)"
citypark.si,"HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.citypark.si', port=443): Read timed out. (read timeout=2)"
ciu.com.uy,"HTTPSConnectionPool(host='ciu.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c9759eb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ciu.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c3b47ee0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ciudaddemendoza.gob.ar,"HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ciudaddemendoza.gob.ar', port=443): Read timed out. (read timeout=2)"
clearnotebooks.com,"HTTPSConnectionPool(host='clearnotebooks.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c7a56df0>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='clearnotebooks.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c221d160>, 'Connection to clearnotebooks.com timed out. (connect timeout=2)'))"
clevelandclinicabudhabi.ae,"HTTPSConnectionPool(host='clevelandclinicabudhabi.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clevelandclinicabudhabi.ae' doesn't match 'www.clevelandclinicabudhabi.ae'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
cloudigirl.com,"HTTPSConnectionPool(host='www.cloudigirl.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.cloudigirl.com', port=443): Read timed out. (read timeout=2)"
cloudnc.fi,"HTTPSConnectionPool(host='cloudnc.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c13ab4c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cloudnc.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c4dfc130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
club-k.net,"HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='club-k.net', port=443): Read timed out. (read timeout=2)"
clubdam.com,"HTTPSConnectionPool(host='clubdam.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8bbe0a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='clubdam.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c22ee0d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
clubedohardware.com.br,"HTTPSConnectionPool(host='www.clubedohardware.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.clubedohardware.com.br', port=443): Read timed out. (read timeout=2)"
clubfactory.com,"HTTPSConnectionPool(host='clubfactory.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c6b7c310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='clubfactory.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c5876f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
clubmb.ee,"HTTPSConnectionPool(host='clubmb.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'clubmb.ee' doesn't match either of 'ns-url-redirect.zoneas.eu', 'www.ns-url-redirect.zoneas.eu'"")))","HTTPSConnectionPool(host='estonia.mercedes-benz-clubs.com', port=443): Read timed out. (read timeout=2)"
cm-oeiras.pt,"HTTPSConnectionPool(host='cm-oeiras.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c4d00940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cm-oeiras.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c61f04f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cm-porto.pt,"HTTPSConnectionPool(host='cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.cm-porto.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
cmru.ac.th,"HTTPSConnectionPool(host='cmru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c1d73b20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cmru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c7493160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cmu.ac.th,"HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='cmu.ac.th', port=443): Read timed out. (read timeout=2)"
cmvm.pt,"HTTPSConnectionPool(host='cmvm.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c22142b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cmvm.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c6b64640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnas.ro,"HTTPSConnectionPool(host='cnas.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c3120250>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnas.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c1076970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cne.go.cr,"HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='cne.go.cr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
cnr.gob.sv,"HTTPSConnectionPool(host='cnr.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8c00b80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnr.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c39c3e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnrs.fr,"HTTPSConnectionPool(host='cnrs.fr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c155aa00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cnrs.fr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c3586c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cnss.ma,"HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))","HTTPSConnectionPool(host='cnss.ma', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cnss.ma' doesn't match either of 'www.cnss.ma', 'www.damancom.ma', 'www.macnss.ma'"")))"
cnu.edu.ni,"HTTPSConnectionPool(host='cnu.edu.ni', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPConnectionPool(host='www.cnu.edu.ni', port=80): Read timed out. (read timeout=2)"
co.ee,"HTTPSConnectionPool(host='co.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c8075e80>, 'Connection to co.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='co.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c22e3400>, 'Connection to co.ee timed out. (connect timeout=2)'))"
cobiss.net,"HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))","HTTPSConnectionPool(host='cobiss.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'cobiss.net' doesn't match either of 'splet04.izum.si', 'www.sicris.si', 'sicris.izum.si', 'webservice.izum.si', 'www.cobiss.net', 'webservice.cobiss.net', 'e-cris.al.cobiss.net', 'e-cris.bg.cobiss.net', 'e-cris.bh.cobiss.net', 'e-cris.cg.cobiss.net', 'e-cris.ko.cobiss.net', 'e-cris.ks.cobiss.net', 'e-cris.mk.cobiss.net', 'e-cris.rs.cobiss.net', 'e-cris.sr.cobiss.net', 'e-cristest.cobiss.net', 'e-prirocniki.izum.si', 'home.izum.si', 'izobrazevanje.izum.si', 'm.cobiss.si', 'm.cobiss.net', 'obrazovanje.ba.cobiss.net', 'obrazovanje.bh.cobiss.net', 'obrazovanje.cg.cobiss.net', 'obrazovanje.rs.cobiss.net', 'obrazovanje.mk.cobiss.net', 'obucenie.bg.cobiss.net', 'trajnimi.al.cobiss.net', 'kualifikimi.al.cobiss.net', 'kualifikimi.ks.cobiss.net'"")))"
cocokarafine.co.jp,"HTTPSConnectionPool(host='cocokarafine.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c4da8790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cocokarafine.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c5e40520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
cocolog-nifty.com,"HTTPSConnectionPool(host='cocolog-nifty.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c9cd94f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='cocolog-nifty.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c3ab93a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
codedfilm.com.ng,"HTTPSConnectionPool(host='codedfilm.com.ng', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='web.codedfilm.com.ng', port=443): Read timed out. (read timeout=2)"
codedwap.com,"HTTPSConnectionPool(host='codedwap.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='codedwapng.com', port=443): Read timed out. (read timeout=2)"
colciencias.gov.co,"HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
coldiretti.it,"HTTPSConnectionPool(host='coldiretti.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c3e28a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='coldiretti.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c1e77730>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
collider.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
colliers.co.nz,"HTTPSConnectionPool(host='colliers.co.nz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.colliers.co.nz', port=443): Read timed out. (read timeout=2)"
combank.lk,"HTTPSConnectionPool(host='combank.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c65cad00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='combank.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c32b4a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
combank.net,"HTTPSConnectionPool(host='combank.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c7cf15b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='combank.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c93d4700>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
commercesuite.com.br,"HTTPSConnectionPool(host='commercesuite.com.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49ca004130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='commercesuite.com.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c884b0d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
companies.lv,"HTTPSConnectionPool(host='companies.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='companies.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
company-information.service.gov.uk,"HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPSConnectionPool(host='company-information.service.gov.uk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))"
companywall.hr,"HTTPSConnectionPool(host='www.companywall.hr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.companywall.hr', port=443): Read timed out. (read timeout=2)"
compumir.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPConnectionPool(host='compumir.ru', port=80): Read timed out. (read timeout=2)"
computerworld.bg,"HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='computerworld.bg', port=443): Read timed out. (read timeout=2)"
comune.re.it,"HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='comune.re.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
comunidadandina.org,"HTTPSConnectionPool(host='comunidadandina.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8156640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='comunidadandina.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c7c8f460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conaf.cl,"HTTPSConnectionPool(host='conaf.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c8132df0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='conaf.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c8bbee80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conare.ac.cr,"HTTPSConnectionPool(host='conare.ac.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49c911e190>, 'Connection to conare.ac.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='conare.ac.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f49c153faf0>, 'Connection to conare.ac.cr timed out. (connect timeout=2)'))"
confidencial.com.ni,Exceeded 30 redirects.,Exceeded 30 redirects.
congreso.gob.pe,"HTTPSConnectionPool(host='congreso.gob.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c98b7d60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='congreso.gob.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c4d007c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
conicyt.cl,"HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.conicyt.cl', port=443): Read timed out. (read timeout=2)"
conjugacion.es,"HTTPSConnectionPool(host='conjugacion.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c38ed9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='conjugacion.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c7e8a6a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
connect.ae,"HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='connect.ae', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
connectselect.be,"HTTPSConnectionPool(host='connectselect.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49c4d52a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='connectselect.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49c4dfcc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
