patefon.co,"HTTPSConnectionPool(host='patefon.co', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='patefon.co', port=443): Read timed out. (read timeout=2)"
patmar.ee,"HTTPSConnectionPool(host='patmar.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='patmar.ee', port=443): Read timed out. (read timeout=2)"
patro.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
pazaruvai-lesno.bg,"HTTPSConnectionPool(host='pazaruvai-lesno.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pazaruvai-lesno.bg', port=443): Read timed out. (read timeout=2)"
pbh.gov.br,"HTTPSConnectionPool(host='pbh.gov.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8811b28340>, 'Connection to pbh.gov.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pbh.gov.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88127a9c40>, 'Connection to pbh.gov.br timed out. (connect timeout=2)'))"
pcfarm.ro,"HTTPSConnectionPool(host='pcfarm.ro', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='pcfarm.ro', port=80): Read timed out. (read timeout=2)"
pctown.co.nz,"HTTPSConnectionPool(host='pctown.co.nz', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='pctown.co.nz', port=80): Read timed out. (read timeout=2)"
pdn.ac.lk,"HTTPSConnectionPool(host='pdn.ac.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88103cde20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pdn.ac.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8811cf3a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
peatus.ee,"HTTPSConnectionPool(host='web.peatus.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='web.peatus.ee', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pedagogica.edu.co,"HTTPSConnectionPool(host='pedagogica.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8813bde1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pedagogica.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8811219fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pegem.net,"HTTPSConnectionPool(host='www.pegem.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pegem.net', port=443): Read timed out. (read timeout=2)"
peixe.com.ar,"HTTPSConnectionPool(host='www.agrupate.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.agrupate.com', port=443): Read timed out. (read timeout=2)"
penang.gov.my,"HTTPSConnectionPool(host='penang.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88100ec3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='penang.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880f920c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
penzin.rs,"HTTPSConnectionPool(host='www.penzin.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.penzin.rs', port=443): Read timed out. (read timeout=2)"
penziony.cz,"HTTPSConnectionPool(host='penziony.cz', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='penziony.cz', port=80): Read timed out. (read timeout=2)"
peoplesbank.lk,"HTTPSConnectionPool(host='peoplesbank.lk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880f7611f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='peoplesbank.lk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880f468550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
perach.org.il,"HTTPSConnectionPool(host='perach.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='perach.org.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
perak.gov.my,"HTTPSConnectionPool(host='perak.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880ec62a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='perak.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8811bf0ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
persee.fr,"HTTPSConnectionPool(host='www.persee.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.persee.fr', port=443): Read timed out. (read timeout=2)"
pertanian.go.id,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
petah-tikva.muni.il,"HTTPSConnectionPool(host='petah-tikva.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8813e7df70>, 'Connection to petah-tikva.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='petah-tikva.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f880fa47970>, 'Connection to petah-tikva.muni.il timed out. (connect timeout=2)'))"
pgdlisboa.pt,"HTTPSConnectionPool(host='pgdlisboa.pt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8811bf03a0>, 'Connection to pgdlisboa.pt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pgdlisboa.pt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f880d6a1ca0>, 'Connection to pgdlisboa.pt timed out. (connect timeout=2)'))"
pgr.gob.ni,"HTTPSConnectionPool(host='pgr.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880c7e4040>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='pgr.gob.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880dc1e1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
pharm16.gr,"HTTPSConnectionPool(host='www.pharm16.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pharm16.gr', port=443): Read timed out. (read timeout=2)"
pharmaline.co.il,"HTTPSConnectionPool(host='pharmaline.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8810c11df0>, 'Connection to pharmaline.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pharmaline.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8811ee49d0>, 'Connection to pharmaline.co.il timed out. (connect timeout=2)'))"
pharmilion.gr,"HTTPSConnectionPool(host='pharmilion.gr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pharmilion.gr', port=443): Read timed out. (read timeout=2)"
pharmindex-online.hu,"HTTPSConnectionPool(host='pharmindex-online.hu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880d6e2880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pharmindex-online.hu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880c62b730>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
phimmoizz.net,"HTTPSConnectionPool(host='phimmoizz.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='phimmoizz.net', port=80): Read timed out. (read timeout=2)"
pichinchacomunicaciones.com.ec,"HTTPSConnectionPool(host='pichinchacomunicaciones.com.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880f9301c0>, 'Connection to pichinchacomunicaciones.com.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pichinchacomunicaciones.com.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88140cb6a0>, 'Connection to pichinchacomunicaciones.com.ec timed out. (connect timeout=2)'))"
pikabu.ru,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
pikiwiki.org.il,"HTTPSConnectionPool(host='www.pikiwiki.org.il', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pikiwiki.org.il', port=443): Read timed out. (read timeout=2)"
pikk.ee,"HTTPSConnectionPool(host='www.pikk.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pikk.ee', port=443): Read timed out. (read timeout=2)"
piluli.ru,"HTTPSConnectionPool(host='piluli.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='piluli.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pirkka.fi,"HTTPSConnectionPool(host='pirkka.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.pirkka.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pitat.com,"HTTPSConnectionPool(host='pitat.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8811ffed30>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='pitat.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880d48f4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
pivnidenicek.cz,"HTTPSConnectionPool(host='pivnidenicek.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'pivnidenicek.cz' doesn't match 'www.pivnidenicek.cz'"")))","HTTPSConnectionPool(host='pivnidenicek.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'pivnidenicek.cz' doesn't match 'www.pivnidenicek.cz'"")))"
pizzasnella.it,"HTTPSConnectionPool(host='pizzasnella.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880a73a1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.pizzasnella.it', port=80): Read timed out. (read timeout=2)"
planalto.gov.br,"HTTPSConnectionPool(host='planalto.gov.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1124)')))","(""Connection broken: ConnectionResetError(104, 'Connection reset by peer')"", ConnectionResetError(104, 'Connection reset by peer'))"
plataformaarquitectura.cl,"HTTPSConnectionPool(host='www.plataformaarquitectura.cl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.plataformaarquitectura.cl', port=443): Read timed out. (read timeout=2)"
pleasantgroveumc.net,"HTTPSConnectionPool(host='pleasantgroveumc.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880b96b820>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pleasantgroveumc.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880deb0520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pmda.go.jp,"HTTPSConnectionPool(host='pmda.go.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8812130100>, 'Connection to pmda.go.jp timed out. (connect timeout=2)'))","HTTPConnectionPool(host='pmda.go.jp', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f880ec7f460>, 'Connection to pmda.go.jp timed out. (connect timeout=2)'))"
pmnewsnigeria.com,"HTTPSConnectionPool(host='pmnewsnigeria.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='pmnewsnigeria.com', port=443): Read timed out. (read timeout=2)"
pnc.gob.sv,"HTTPSConnectionPool(host='pnc.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8811873a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pnc.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880a5a9670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pnp.co.za,"HTTPSConnectionPool(host='pnp.co.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f881255f700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='pnp.co.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8812266640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
poder-judicial.go.cr,"HTTPSConnectionPool(host='poder-judicial.go.cr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880deb0430>, 'Connection to poder-judicial.go.cr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='poder-judicial.go.cr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f880f6d8820>, 'Connection to poder-judicial.go.cr timed out. (connect timeout=2)'))"
poderjudicial.gob.ni,"HTTPSConnectionPool(host='poderjudicial.gob.ni', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880b950b80>, 'Connection to poderjudicial.gob.ni timed out. (connect timeout=2)'))","HTTPConnectionPool(host='poderjudicial.gob.ni', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f880a71b250>, 'Connection to poderjudicial.gob.ni timed out. (connect timeout=2)'))"
poduckun.net,"HTTPSConnectionPool(host='poduckun.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='poduckun.net', port=443): Read timed out. (read timeout=2)"
poipeplekkers.be,"HTTPSConnectionPool(host='poipeplekkers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8811d4e640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='poipeplekkers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880a7759a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
poisci.me,"HTTPSConnectionPool(host='poisci.me', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='poisci.me', port=80): Read timed out. (read timeout=2)"
polazak.rs,Exceeded 30 redirects.,Exceeded 30 redirects.
policia.gov.co,"HTTPSConnectionPool(host='policia.gov.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f880e9e1e80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='policia.gov.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880b9e7190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
polito.it,"HTTPSConnectionPool(host='polito.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f881397c460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='polito.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88073fcd60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
polsl.pl,"HTTPSConnectionPool(host='polsl.pl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8813f74ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='polsl.pl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880a5a9490>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
pom.go.id,"HTTPSConnectionPool(host='pom.go.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='pom.go.id', port=443): Max retries exceeded with url: /new/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
pontofrio.com.br,"HTTPSConnectionPool(host='www.pontofrio.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.pontofrio.com.br', port=443): Read timed out. (read timeout=2)"
popcornfor2.com,"HTTPSConnectionPool(host='popcornfor2.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='popcornfor2.com', port=80): Read timed out. (read timeout=2)"
popmama.com,"HTTPSConnectionPool(host='popmama.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='popmama.com', port=80): Read timed out. (read timeout=2)"
poradnikogrodniczy.pl,"HTTPSConnectionPool(host='poradnikogrodniczy.pl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f88114e92e0>, 'Connection to poradnikogrodniczy.pl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='poradnikogrodniczy.pl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f881349a820>, 'Connection to poradnikogrodniczy.pl timed out. (connect timeout=2)'))"
porezna-uprava.hr,"HTTPSConnectionPool(host='porezna-uprava.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88115cdc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='porezna-uprava.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f880d6eba00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
portal.gov.bd,"HTTPSConnectionPool(host='portal.gov.bd', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='portal.gov.bd', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
portaldasfinancas.gov.pt,"HTTPSConnectionPool(host='portaldasfinancas.gov.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8811a4b160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='portaldasfinancas.gov.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f881071f400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
portorecanaticalcio.it,"HTTPSConnectionPool(host='www.portorecanaticalcio.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.portorecanaticalcio.it', port=443): Read timed out. (read timeout=2)"
postaonline.cz,"HTTPConnectionPool(host='www.postaonline.cz', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='postaonline.cz', port=80): Read timed out. (read timeout=2)"
posted.co.rs,"HTTPSConnectionPool(host='posted.co.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8808fa0a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='posted.co.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8812a92310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
pozitivke.net,"HTTPSConnectionPool(host='pozitivke.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'pozitivke.net' doesn't match either of '*.mojhost.net', 'mojhost.net'"")))","HTTPConnectionPool(host='pozitivke.net', port=80): Read timed out. (read timeout=2)"
