recepti.pl,"HTTPSConnectionPool(host='recepti.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.recepti.pl', port=443): Read timed out. (read timeout=2)"
receptizasvakog.com,"HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='receptizasvakog.com', port=443): Read timed out. (read timeout=2)"
receptkollekcio.com,"HTTPSConnectionPool(host='receptkollekcio.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918aa4ba60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='receptkollekcio.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918a843ee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
recruit.se,"HTTPSConnectionPool(host='recruit.se', port=443): Read timed out.","HTTPConnectionPool(host='recruit.se', port=80): Read timed out."
redcross.or.th,"HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))","HTTPSConnectionPool(host='redcross.or.th', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))"
referat.ro,"HTTPSConnectionPool(host='referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.referat.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
refertimacuan.com,"HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='refertimacuan.com', port=443): Read timed out. (read timeout=2)"
regionalobala.si,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
regione.fvg.it,"HTTPSConnectionPool(host='regione.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918ac747f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='regione.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918ceaa7f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
regione.piemonte.it,"HTTPSConnectionPool(host='regione.piemonte.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918a8dae80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='regione.piemonte.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918a0d6850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
registraduria.gov.co,"HTTPSConnectionPool(host='registraduria.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f918a86d4c0>, 'Connection to registraduria.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='registraduria.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f91889fdf40>, 'Connection to registraduria.gov.co timed out. (connect timeout=2)'))"
rei.com,"HTTPSConnectionPool(host='rei.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='rei.com', port=80): Read timed out. (read timeout=2)"
repositorioinstitucional.mx,"HTTPSConnectionPool(host='repositorioinstitucional.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918b370640>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='repositorioinstitucional.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918871f7c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rero.ch,"HTTPSConnectionPool(host='rero.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rero.ch' doesn't match either of 'www.rero.ch', '*.rero.ch', '*.test.rero.ch'"")))","HTTPSConnectionPool(host='www.rero.ch', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
reseau-canope.fr,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
resepmasakanku.net,"HTTPSConnectionPool(host='resepmasakanku.net', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='resepmasakanku.net', port=80): Read timed out. (read timeout=2)"
resett.no,"HTTPSConnectionPool(host='resett.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='resett.no', port=443): Read timed out. (read timeout=2)"
rest.co.il,"HTTPSConnectionPool(host='rest.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.rest.co.il', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
retikul.hu,"HTTPSConnectionPool(host='www.retikul.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.retikul.hu', port=443): Read timed out. (read timeout=2)"
revistaei.cl,"HTTPSConnectionPool(host='revistaei.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918c9f4820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='revistaei.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9188f7fcd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ribeiro.com.ar,"HTTPSConnectionPool(host='ribeiro.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ribeiro.com.ar' doesn't match '*.ribeiro.com.ar'"")))","HTTPSConnectionPool(host='ribeiro.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ribeiro.com.ar' doesn't match '*.ribeiro.com.ar'"")))"
ric.si,"HTTPSConnectionPool(host='ric.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918ceaa610>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ric.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918a92acd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
richmondfuture.org,"HTTPSConnectionPool(host='richmondfuture.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918b0f6790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='richmondfuture.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918c869d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
rickid.nl,"HTTPSConnectionPool(host='rickid.nl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918cf6cfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='rickid.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918cd6b610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
rikunabi.com,"HTTPSConnectionPool(host='rikunabi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9184f06fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rikunabi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9184d81850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rington.io,"HTTPSConnectionPool(host='rington.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPConnectionPool(host='rington.io', port=80): Read timed out. (read timeout=2)"
rishonlezion.muni.il,"HTTPSConnectionPool(host='rishonlezion.muni.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9184b7d040>, 'Connection to rishonlezion.muni.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rishonlezion.muni.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f918508c370>, 'Connection to rishonlezion.muni.il timed out. (connect timeout=2)'))"
ristekdikti.go.id,"HTTPSConnectionPool(host='ristekdikti.go.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f91873e9850>, 'Connection to ristekdikti.go.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ristekdikti.go.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9184e76310>, 'Connection to ristekdikti.go.id timed out. (connect timeout=2)'))"
ritsumei.ac.jp,"HTTPSConnectionPool(host='ritsumei.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918537a4f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ritsumei.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918c725550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rivera.gub.uy,"HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='rivera.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
rmutr.ac.th,"HTTPSConnectionPool(host='rmutr.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918c34a130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rmutr.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918c977760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
robsoft.nu,"HTTPSConnectionPool(host='robsoft.nu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f91851ecd60>, 'Connection to robsoft.nu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='robsoft.nu', port=80): Read timed out. (read timeout=2)"
rockol.it,"HTTPSConnectionPool(host='rockol.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f918acee130>, 'Connection to rockol.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='rockol.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f918c21fcd0>, 'Connection to rockol.it timed out. (connect timeout=2)'))"
roditelji.me,"HTTPSConnectionPool(host='www.roditelji.me', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.roditelji.me', port=443): Read timed out. (read timeout=2)"
rollingpin.at,"HTTPSConnectionPool(host='www.rollingpin.at', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rollingpin.at', port=443): Read timed out. (read timeout=2)"
rotise.gr,"HTTPSConnectionPool(host='rotise.gr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))",Exceeded 30 redirects.
roundmenu.com,"HTTPSConnectionPool(host='www.roundmenu.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.roundmenu.com', port=443): Read timed out. (read timeout=2)"
rozali.com,"HTTPSConnectionPool(host='rozali.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='rozali.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
rri.ro,"HTTPSConnectionPool(host='rri.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rri.ro' doesn't match 'www.rri.ro'"")))","HTTPSConnectionPool(host='www.rri.ro', port=443): Read timed out. (read timeout=2)"
rs-online.com,"HTTPSConnectionPool(host='rs-online.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9184fa4a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rs-online.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9188f7f8e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rs.ba,"HTTPSConnectionPool(host='rs.ba', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91843b38b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rs.ba', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f91828ea6d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rspdf.info,"HTTPSConnectionPool(host='rspdf.info', port=443): Read timed out.","HTTPSConnectionPool(host='rspdf.info', port=443): Read timed out."
rsvid.info,"HTTPSConnectionPool(host='rsvid.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='rsvid.info', port=443): Read timed out. (read timeout=2)"
rtk.rs,"HTTPSConnectionPool(host='www.rtk.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rtk.rs', port=443): Read timed out. (read timeout=2)"
rtm.gov.my,"HTTPSConnectionPool(host='rtm.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91889c5310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rtm.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918ba0fb20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rttuotetieto.fi,"HTTPSConnectionPool(host='rttuotetieto.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'rttuotetieto.fi' doesn't match either of 'www.rttuotetieto.fi', 'urakoitsija.rttuotetieto.fi'"")))","HTTPSConnectionPool(host='www.rttuotetieto.fi', port=443): Read timed out. (read timeout=2)"
rtvbudva.me,"HTTPSConnectionPool(host='www.rtvbudva.me', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.rtvbudva.me', port=443): Read timed out. (read timeout=2)"
rtvmag.co.rs,"HTTPSConnectionPool(host='rtvmag.co.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91850a55b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rtvmag.co.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9182617e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ru.ac.th,"HTTPSConnectionPool(host='ru.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918b20bd60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ru.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918acbe550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rumahbelajar.id,"HTTPSConnectionPool(host='rumahbelajar.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918647d340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='rumahbelajar.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918b0adfa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ruten.com.tw,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
rvb.lt,"HTTPSConnectionPool(host='rvb.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9187c07850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='rvb.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9188c3d550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
rvvg.lv,"HTTPSConnectionPool(host='rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.rvvg.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
rzp.cz,"HTTPSConnectionPool(host='rzp.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))","HTTPConnectionPool(host='rzp.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f918b2f5670>, 'Connection to rzp.cz timed out. (connect timeout=2)'))"
s-ge.com,"HTTPSConnectionPool(host='www.s-ge.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.s-ge.com', port=443): Read timed out. (read timeout=2)"
saabturboclub.com,"HTTPSConnectionPool(host='saabturboclub.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9184e9c130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='saabturboclub.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9186303430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sabcnews.com,"HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sabcnews.com', port=443): Read timed out. (read timeout=2)"
saberingles.com.ar,"HTTPSConnectionPool(host='saberingles.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1131)')))","HTTPConnectionPool(host='saberingles.com.ar', port=80): Read timed out. (read timeout=2)"
sachvui.com,"HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sachvui.com', port=443): Read timed out. (read timeout=2)"
sahibinden.com,"HTTPSConnectionPool(host='sahibinden.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahibinden.com', port=80): Read timed out. (read timeout=2)"
sahibinden.com.tr,"HTTPSConnectionPool(host='sahibinden.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1131)')))","HTTPConnectionPool(host='sahibinden.com.tr', port=80): Read timed out. (read timeout=2)"
sahra.org.za,"HTTPSConnectionPool(host='sahra.org.za', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sahra.org.za', port=80): Read timed out. (read timeout=2)"
saitama.lg.jp,"HTTPSConnectionPool(host='saitama.lg.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f918879b880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='saitama.lg.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f918a6ac5e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
salary.com,"HTTPSConnectionPool(host='salary.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='salary.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
saldus.lv,"HTTPSConnectionPool(host='saldus.lv', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9184b59b80>, 'Connection to saldus.lv timed out. (connect timeout=2)'))","HTTPConnectionPool(host='saldus.lv', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f91839d4820>, 'Connection to saldus.lv timed out. (connect timeout=2)'))"
salika.co,"HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))","HTTPSConnectionPool(host='salika.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salika.co' doesn't match 'www.salika.co'"")))"
