salud.gob.ec,"HTTPSConnectionPool(host='salud.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salud.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
salud.gob.mx,"HTTPSConnectionPool(host='salud.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d688a160>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='salud.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d688a730>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))"
sama.gov.sa,"HTTPSConnectionPool(host='sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samrate.com,"HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samregion.ru,"HTTPSConnectionPool(host='samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanborns.com.mx,"HTTPSConnectionPool(host='sanborns.com.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sanborns.com.mx', port=443): Read timed out. (read timeout=2)"
sangfans.com,"HTTPSConnectionPool(host='sangfans.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sangfans.com', port=443): Read timed out. (read timeout=2)"
sanita.fvg.it,"HTTPSConnectionPool(host='sanita.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d3ed8e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanita.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d68fde20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanita.puglia.it,"HTTPSConnectionPool(host='sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanitex.eu,"HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
santander.cl,"HTTPSConnectionPool(host='santander.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d3add7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santander.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3addf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sante.gov.ma,"HTTPSConnectionPool(host='sante.gov.ma', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d56c6f10>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sante.gov.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d37cc970>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))"
santos.sp.gov.br,"HTTPSConnectionPool(host='santos.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d4e80070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santos.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d4389b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
santotomas.cl,"HTTPSConnectionPool(host='santotomas.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d5732fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santotomas.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d474b580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanu.ac.rs,"HTTPSConnectionPool(host='sanu.ac.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d510d700>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sanu.ac.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d3856fa0>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))"
sanyonews.jp,"HTTPSConnectionPool(host='sanyonews.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d4d3f9a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanyonews.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d31e1fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saostar.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
saps.gov.za,"HTTPSConnectionPool(host='saps.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d31f9070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saps.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d2faafd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarandi690.com.uy,"HTTPSConnectionPool(host='sarandi690.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d3856910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sarandi690.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3991af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarawak.gov.my,"HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)"
sarkiyukleindir.com,"HTTPSConnectionPool(host='sarkiyukleindir.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarkiyukleindir.com', port=443): Read timed out."
satofull.jp,"HTTPSConnectionPool(host='satofull.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d5459550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satofull.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3cd9b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
satori.lv,"HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)"
satriwit3.ac.th,"HTTPSConnectionPool(host='satriwit3.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d2d5c580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satriwit3.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d44f4340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
savba.sk,"HTTPSConnectionPool(host='savba.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d208a9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='savba.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d6808700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sayellow.com,"HTTPSConnectionPool(host='sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sbc.org.pl,"HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)"
sbi.co.in,"HTTPSConnectionPool(host='sbi.co.in', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d48c3a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sbi.co.in', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d21d41f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sbp.com.br,"HTTPSConnectionPool(host='sbp.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d31f9430>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sbp.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d0e2ff70>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))"
sbp.org.pk,"HTTPSConnectionPool(host='sbp.org.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d40b9880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sbp.org.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d21c75e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sc-celje.si,"HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)"
scba.gov.ar,"HTTPSConnectionPool(host='scba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d622fb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d0559670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sch.in.ua,"HTTPSConnectionPool(host='sch.in.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d28be430>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='schoolchampion.in.ua', port=80): Read timed out. (read timeout=2)"
schip.io,"HTTPSConnectionPool(host='schip.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d63fa3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='schip.io', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d025dd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.bo,"HTTPSConnectionPool(host='scielo.org.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cf95cf40>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='scielo.org.bo', port=80): Read timed out. (read timeout=2)"
scielo.org.co,"HTTPSConnectionPool(host='scielo.org.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d5aff2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d0089820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.pe,"HTTPSConnectionPool(host='scielo.org.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d5e402b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d0559b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.za,"HTTPSConnectionPool(host='scielo.org.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d4dd2160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81cfa60310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.sa.cr,"HTTPSConnectionPool(host='scielo.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d40ca460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3e92f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scjn.gob.mx,"HTTPSConnectionPool(host='scjn.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d62a5040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scjn.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d05591f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scoilnet.ie,"HTTPSConnectionPool(host='scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
scotiabank.com.uy,"HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))","HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))"
scotiabankcolpatria.com,"HTTPSConnectionPool(host='scotiabankcolpatria.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cf3ca4f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scotiabankcolpatria.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d0297a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
screenrant.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scv.si,"HTTPSConnectionPool(host='scv.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cf375dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scv.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81ceb600d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sdetmi.com,"HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)"
sdp.gov.co,"HTTPSConnectionPool(host='sdp.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d5a34be0>, 'Connection to sdp.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sdp.gov.co', port=80): Read timed out. (read timeout=2)"
seattletimes.com,"HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)"
sec.or.th,"HTTPSConnectionPool(host='sec.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d31905b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sec.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81cf3758e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
secure-folders.com,"HTTPConnectionPool(host='www.secure-folders.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.secure-folders.com', port=80): Read timed out. (read timeout=2)"
seebiz.eu,"HTTPSConnectionPool(host='seebiz.eu', port=443): Read timed out.","HTTPSConnectionPool(host='www.seebiz.eu', port=443): Read timed out."
seedly.sg,"HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)"
sefaria.org,"HTTPSConnectionPool(host='www.sefaria.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sefaria.org', port=443): Read timed out. (read timeout=2)"
seguridadpublica.go.cr,"HTTPSConnectionPool(host='seguridadpublica.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cde6db80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='seguridadpublica.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d419c4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sej.co.jp,"HTTPSConnectionPool(host='sej.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cd6e3fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sej.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d606c310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
selangor.gov.my,"HTTPSConnectionPool(host='selangor.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cd5f1100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='selangor.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d68d63a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
semarnat.gob.mx,"HTTPSConnectionPool(host='semarnat.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81ceaaa730>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='semarnat.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81cee0d220>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))"
semmelweis.hu,"HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)"
sena.edu.co,"HTTPSConnectionPool(host='sena.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d3bf80d0>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sena.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81cdc04280>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))"
senac.br,"HTTPSConnectionPool(host='senac.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d4474a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senac.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d532d7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senado.gob.mx,"HTTPSConnectionPool(host='senado.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81ceb609d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senado.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81cdbfa400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senate.go.th,"HTTPSConnectionPool(host='senate.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d0ffc4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senate.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3af4d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sephora.fr,"HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)"
sephora.pl,"HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)"
sephora.sa,"HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)"
sephora.sg,"HTTPSConnectionPool(host='www.sephora.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sg', port=443): Read timed out. (read timeout=2)"
sepyc.gob.mx,"HTTPSConnectionPool(host='sepyc.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81ceac0190>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sepyc.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81cf375eb0>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))"
sernac.cl,"HTTPSConnectionPool(host='sernac.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81ccc51c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sernac.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81ccbe6070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
set.edu.br,"HTTPSConnectionPool(host='set.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d579fb80>, 'Connection to set.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='set.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d3916b20>, 'Connection to set.edu.br timed out. (connect timeout=2)'))"
sgg.gov.ma,"HTTPSConnectionPool(host='sgg.gov.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d597cf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sgg.gov.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81ccccd2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sggw.pl,"HTTPSConnectionPool(host='sggw.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='sggw.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sgk.gov.tr,"HTTPSConnectionPool(host='sgk.gov.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d57d7a60>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.sgk.gov.tr', port=80): Read timed out. (read timeout=2)"
shabex.ch,"HTTPSConnectionPool(host='www.shabex.ch', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shabex.ch', port=443): Read timed out. (read timeout=2)"
shamechorus.com,"HTTPSConnectionPool(host='shamechorus.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='shamechorus.com', port=80): Read timed out. (read timeout=2)"
sharp.co.jp,"HTTPSConnectionPool(host='sharp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d4880be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sharp.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d43c0100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
shd.gov.co,"HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
shop.by,"HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)"
shoptime.com.br,"HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)"
showcase-tv.com,"HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))","HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))"
shufersal.co.il,"HTTPSConnectionPool(host='shufersal.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81cdd99af0>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shufersal.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81cccda2b0>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))"
siauliuraj.lt,"HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))","HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))"
sib.gob.gt,"HTTPSConnectionPool(host='sib.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d0002b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sib.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d3ae7d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sic.gov.co,"HTTPSConnectionPool(host='sic.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d38c2cd0>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sic.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81cdfe8b20>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))"
sicad.gov.tn,"HTTPSConnectionPool(host='sicad.gov.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81ccdb4610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sicad.gov.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81d4343430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sigmaaldrich.com,"HTTPSConnectionPool(host='sigmaaldrich.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sigmaaldrich.com' doesn't match either of 'www.sigmaaldrich.com', 'www.sigma-aldrich.com'"")))","HTTPSConnectionPool(host='www.sigmaaldrich.com', port=443): Read timed out. (read timeout=2)"
signe-moi.com,"HTTPSConnectionPool(host='signe-moi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81d5faa790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='signe-moi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81ceb995e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sii.cl,"HTTPSConnectionPool(host='sii.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f81d551a1f0>, 'Connection to sii.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sii.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f81d68fd940>, 'Connection to sii.cl timed out. (connect timeout=2)'))"
sik.si,"HTTPSConnectionPool(host='sik.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f81cdb91160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sik.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81cce2a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
singaporeair.com,"HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)"
singaporelegaladvice.com,"HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)"
singaporemotherhood.com,"HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)"
sipdf.info,"HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out.","HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out."
sirvintos.lt,"HTTPSConnectionPool(host='sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sis.gov.eg,"HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
