salud.gob.ec,"HTTPSConnectionPool(host='salud.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salud.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
salud.gob.mx,"HTTPSConnectionPool(host='salud.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09ffff8610>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='salud.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09ffff8be0>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))"
sama.gov.sa,"HTTPSConnectionPool(host='sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
samrate.com,"HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
samregion.ru,"HTTPSConnectionPool(host='samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sangfans.com,"HTTPSConnectionPool(host='sangfans.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sangfans.com', port=443): Read timed out. (read timeout=2)"
sanita.fvg.it,"HTTPSConnectionPool(host='sanita.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fdd19e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sanita.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fe960dc0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sanita.puglia.it,"HTTPSConnectionPool(host='sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sanitex.eu,"HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
santander.cl,"HTTPSConnectionPool(host='santander.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ffe80f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='santander.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fda530a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sante.gov.ma,"HTTPSConnectionPool(host='sante.gov.ma', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09fd0ac8b0>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sante.gov.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09fe388580>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))"
santos.sp.gov.br,"HTTPSConnectionPool(host='santos.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe925190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='santos.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd7ffb50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
santotomas.cl,"HTTPSConnectionPool(host='santotomas.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe8c24f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='santotomas.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd158190>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sanu.ac.rs,"HTTPSConnectionPool(host='sanu.ac.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09fe90aa00>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sanu.ac.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09fe1d5b50>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))"
sanyonews.jp,"HTTPSConnectionPool(host='sanyonews.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fd6987c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sanyonews.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd4327c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
saostar.vn,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
sapo.pt,"HTTPSConnectionPool(host='www.sapo.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sapo.pt', port=443): Read timed out. (read timeout=2)"
saps.gov.za,"HTTPSConnectionPool(host='saps.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe39bbe0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='saps.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd14d400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sarawak.gov.my,"HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)"
sarkisozlerihd.com,"HTTPSConnectionPool(host='www.sarkisozlerihd.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sarkisozlerihd.com', port=443): Read timed out. (read timeout=2)"
sarkiyukleindir.com,"HTTPSConnectionPool(host='sarkiyukleindir.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarkiyukleindir.com', port=443): Read timed out. (read timeout=2)"
sat.gob.mx,"HTTPSConnectionPool(host='sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='wwwmat.sat.gob.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
satofull.jp,"HTTPSConnectionPool(host='satofull.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ff18e040>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='satofull.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fce18d60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
satori.lv,"HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)"
satriwit3.ac.th,"HTTPSConnectionPool(host='satriwit3.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fc874fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='satriwit3.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd8d1fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
savba.sk,"HTTPSConnectionPool(host='savba.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fdf4dbb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='savba.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ff246a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sawahpress.com,"HTTPSConnectionPool(host='sawahpress.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sawahpress.com', port=80): Read timed out. (read timeout=2)"
sayellow.com,"HTTPSConnectionPool(host='sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sayellow.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sbc.org.pl,"HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)"
sbp.com.br,"HTTPSConnectionPool(host='sbp.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09fe2fe5b0>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sbp.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09fe42d130>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))"
sbp.org.pk,"HTTPSConnectionPool(host='sbp.org.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fd143d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sbp.org.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ffd9c310>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sc-celje.si,"HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)"
scba.gov.ar,"HTTPSConnectionPool(host='scba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe3b7e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fb4e1f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sch.in.ua,"HTTPSConnectionPool(host='sch.in.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fd143130>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='schoolchampion.in.ua', port=80): Read timed out. (read timeout=2)"
schip.io,"HTTPSConnectionPool(host='schip.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ff893970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='schip.io', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ff9c06d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scielo.org.co,"HTTPSConnectionPool(host='scielo.org.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ff2b0d90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scielo.org.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ffd10970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scielo.org.pe,"HTTPSConnectionPool(host='scielo.org.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe696a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scielo.org.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fdbf1f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scielo.org.za,"HTTPSConnectionPool(host='scielo.org.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fb4baeb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scielo.org.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fb21d2b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scielo.sa.cr,"HTTPSConnectionPool(host='scielo.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fb23efa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scielo.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fb39aaf0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scjn.gob.mx,"HTTPSConnectionPool(host='scjn.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fb39ab80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scjn.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fb462f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
scoilnet.ie,"HTTPSConnectionPool(host='scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
scotiabank.com.uy,"HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))","HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))"
scotiabankcolpatria.com,"HTTPSConnectionPool(host='scotiabankcolpatria.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fa732fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scotiabankcolpatria.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09faeeeaf0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
screenrant.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scumc.ro,"HTTPSConnectionPool(host='scumc.ro', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ffa37370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='scumc.ro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fda5f5b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
scv.si,"HTTPSConnectionPool(host='scv.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fa5e1f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='scv.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fdcadc40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sdetmi.com,"HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)"
sears.com,"HTTPSConnectionPool(host='sears.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sears.com', port=80): Read timed out. (read timeout=2)"
seattletimes.com,"HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)"
sec.or.th,"HTTPSConnectionPool(host='sec.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fbffb2b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sec.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd5e09d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
secretcv.com,"HTTPSConnectionPool(host='secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.secretcv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
secure-folders.com,"HTTPConnectionPool(host='www.secure-folders.com', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='secure-folders.com', port=80): Read timed out. (read timeout=2)"
seedly.sg,"HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)"
segeplan.gob.gt,"HTTPSConnectionPool(host='segeplan.gob.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'segeplan.gob.gt' doesn't match either of '*.segeplan.gob.gt', 'www.segeplan.gob.gt'"")))","HTTPSConnectionPool(host='www.segeplan.gob.gt', port=443): Read timed out. (read timeout=2)"
seguridadpublica.go.cr,"HTTPSConnectionPool(host='seguridadpublica.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fffb5430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='seguridadpublica.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fd5e03a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sej.co.jp,"HTTPSConnectionPool(host='sej.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09f9c40850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sej.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fe4d1970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
selangor.gov.my,"HTTPSConnectionPool(host='selangor.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09f9b14cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='selangor.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fa620d90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
semarnat.gob.mx,"HTTPSConnectionPool(host='semarnat.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09ff09f4c0>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='semarnat.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09fd5e0e80>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))"
semmelweis.hu,"HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)"
senac.br,"HTTPSConnectionPool(host='senac.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09feb49160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='senac.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09f9a03e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
senado.gob.mx,"HTTPSConnectionPool(host='senado.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fc28bf10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='senado.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09f9838a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
senate.go.th,"HTTPSConnectionPool(host='senate.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe37a520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='senate.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fe2e41f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sephora.fr,"HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)"
sephora.pl,"HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)"
sephora.sa,"HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)"
sernac.cl,"HTTPSConnectionPool(host='sernac.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09f86e87f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sernac.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09f8bd4460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
servina.net,"HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)"
set.edu.br,"HTTPSConnectionPool(host='set.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09fa7c0f10>, 'Connection to set.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='set.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09f8f4d070>, 'Connection to set.edu.br timed out. (connect timeout=2)'))"
sfax.com.tn,"HTTPSConnectionPool(host='sfax.com.tn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sfax.com.tn' doesn't match either of 'cpanel.sfax.com.tn', 'cpcalendars.sfax.com.tn', 'cpcontacts.sfax.com.tn', 'mail.sfax.com.tn', 'webdisk.sfax.com.tn', 'webmail.sfax.com.tn', 'www.sfax.com.tn'"")))","HTTPConnectionPool(host='sfax.com.tn', port=80): Read timed out. (read timeout=2)"
sfp.org.pl,"HTTPSConnectionPool(host='sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sfp.org.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
sgg.gov.ma,"HTTPSConnectionPool(host='sgg.gov.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09f8c8c3a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sgg.gov.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fe2bc6a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sggw.pl,"HTTPSConnectionPool(host='sggw.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1131)')))","HTTPSConnectionPool(host='sggw.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sgk.gov.tr,"HTTPSConnectionPool(host='sgk.gov.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09feb49970>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.sgk.gov.tr', port=80): Read timed out. (read timeout=2)"
sgmagazine.com,"HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='sgmagazine.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
shamechorus.com,"HTTPSConnectionPool(host='shamechorus.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='shamechorus.com', port=80): Read timed out. (read timeout=2)"
sharp.co.jp,"HTTPSConnectionPool(host='sharp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ff4ed7f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sharp.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fdd39f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
shd.gov.co,"HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
shop.by,"HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)"
shoptime.com.br,"HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)"
showcase-tv.com,"HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))","HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))"
shtreber.com,"HTTPSConnectionPool(host='www.shtreber.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shtreber.com', port=443): Read timed out. (read timeout=2)"
siauliuraj.lt,"HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))","HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))"
sib.gob.gt,"HTTPSConnectionPool(host='sib.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fe90ad00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sib.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09f6d67f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sic.gov.co,"HTTPSConnectionPool(host='sic.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sic.gov.co' doesn't match 'www.sic.gov.co'"")))","HTTPConnectionPool(host='sic.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09ff3f6c10>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))"
sicad.gov.tn,"HTTPSConnectionPool(host='sicad.gov.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09ffb177c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sicad.gov.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09fa36dfa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
sieviesuklubs.lv,"HTTPSConnectionPool(host='sieviesuklubs.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1131)')))","HTTPConnectionPool(host='www.sieviesuklubs.lv', port=80): Read timed out. (read timeout=2)"
sigmaaldrich.com,"HTTPSConnectionPool(host='sigmaaldrich.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'sigmaaldrich.com' doesn't match either of 'www.sigmaaldrich.com', 'www.sigma-aldrich.com'"")))","HTTPSConnectionPool(host='www.sigmaaldrich.com', port=443): Read timed out. (read timeout=2)"
signe-moi.com,"HTTPSConnectionPool(host='signe-moi.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09f7636070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='signe-moi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09f8b26f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
significadosbr.com.br,"HTTPSConnectionPool(host='significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.significadosbr.com.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
sigulda.lv,"HTTPSConnectionPool(host='www.sigulda.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sigulda.lv', port=443): Read timed out. (read timeout=2)"
sii.cl,"HTTPSConnectionPool(host='sii.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09ff858a00>, 'Connection to sii.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sii.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f09fc874f40>, 'Connection to sii.cl timed out. (connect timeout=2)'))"
sik.si,"HTTPSConnectionPool(host='sik.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09fa6d6880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='sik.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09ff152070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
singaporeair.com,"HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)"
singaporelegaladvice.com,"HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)"
singaporemotherhood.com,"HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)"
sipdf.info,"HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out.","HTTPSConnectionPool(host='sipdf.info', port=443): Read timed out."
sirvintos.lt,"HTTPSConnectionPool(host='sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sis.gov.eg,"HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
sistory.si,"HTTPSConnectionPool(host='sistory.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sistory.si', port=443): Read timed out. (read timeout=2)"
sitemercado.com.br,"HTTPSConnectionPool(host='www.sitemercado.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sitemercado.com.br', port=443): Read timed out. (read timeout=2)"
