salud.gob.ec,"HTTPSConnectionPool(host='salud.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'salud.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
salud.gob.mx,"HTTPSConnectionPool(host='salud.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5867a3d0>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='salud.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a5867a9a0>, 'Connection to salud.gob.mx timed out. (connect timeout=2)'))"
sama.gov.sa,"HTTPSConnectionPool(host='sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sama.gov.sa', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samrate.com,"HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='samrate.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
samregion.ru,"HTTPSConnectionPool(host='samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.samregion.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sangfans.com,"HTTPSConnectionPool(host='sangfans.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sangfans.com', port=443): Read timed out. (read timeout=2)"
sanita.fvg.it,"HTTPSConnectionPool(host='sanita.fvg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a583add90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanita.fvg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5842af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanita.puglia.it,"HTTPSConnectionPool(host='sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sanita.puglia.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sanitex.eu,"HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sanitex.eu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
santander.cl,"HTTPSConnectionPool(host='santander.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582b91c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santander.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58359460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sante.gov.ma,"HTTPSConnectionPool(host='sante.gov.ma', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a582ad220>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sante.gov.ma', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a58744af0>, 'Connection to sante.gov.ma timed out. (connect timeout=2)'))"
santos.sp.gov.br,"HTTPSConnectionPool(host='santos.sp.gov.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582ed970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santos.sp.gov.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58218a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
santotomas.cl,"HTTPSConnectionPool(host='santotomas.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58359d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='santotomas.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5834e640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sanu.ac.rs,"HTTPSConnectionPool(host='sanu.ac.rs', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5846eb80>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sanu.ac.rs', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a5834e070>, 'Connection to sanu.ac.rs timed out. (connect timeout=2)'))"
sanyonews.jp,"HTTPSConnectionPool(host='sanyonews.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a581c60d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sanyonews.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5843a190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
saps.gov.za,"HTTPSConnectionPool(host='saps.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58267ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='saps.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5834ec10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarandi690.com.uy,"HTTPSConnectionPool(host='sarandi690.com.uy', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582e1d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sarandi690.com.uy', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a582f0520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sarawak.gov.my,"HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sarawak.gov.my', port=443): Read timed out. (read timeout=2)"
satofull.jp,"HTTPSConnectionPool(host='satofull.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a583ad850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satofull.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58366e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
satori.lv,"HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='satori.lv', port=443): Read timed out. (read timeout=2)"
satriwit3.ac.th,"HTTPSConnectionPool(host='satriwit3.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58366d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='satriwit3.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a582e11c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
savba.sk,"HTTPSConnectionPool(host='savba.sk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a583e75e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='savba.sk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a583e7c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sawadee.co.th,"HTTPSConnectionPool(host='sawadee.co.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5846ef70>, 'Connection to sawadee.co.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sawadee.co.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a58267700>, 'Connection to sawadee.co.th timed out. (connect timeout=2)'))"
sbc.org.pl,"HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sbc.org.pl', port=443): Read timed out. (read timeout=2)"
sbp.com.br,"HTTPSConnectionPool(host='sbp.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a58389eb0>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sbp.com.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a580a4b80>, 'Connection to sbp.com.br timed out. (connect timeout=2)'))"
sbp.org.pk,"HTTPSConnectionPool(host='sbp.org.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a581603d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sbp.org.pk', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a580dc370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sc-celje.si,"HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sc-celje.si', port=443): Read timed out. (read timeout=2)"
scandichotels.fi,"HTTPSConnectionPool(host='scandichotels.fi', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5804b2b0>, 'Connection to scandichotels.fi timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='www.scandichotels.fi', port=443): Read timed out. (read timeout=2)"
scba.gov.ar,"HTTPSConnectionPool(host='scba.gov.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58343be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scba.gov.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58060940>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sch.in.ua,"HTTPSConnectionPool(host='sch.in.ua', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58060d30>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='schoolchampion.in.ua', port=80): Read timed out. (read timeout=2)"
schip.io,"HTTPSConnectionPool(host='schip.io', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582248b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='schip.io', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5804be50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.br,"HTTPSConnectionPool(host='scielo.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.scielo.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
scielo.org.bo,"HTTPSConnectionPool(host='scielo.org.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58223df0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='scielo.org.bo', port=80): Read timed out. (read timeout=2)"
scielo.org.co,"HTTPSConnectionPool(host='scielo.org.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57f9ffa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58154070>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.mx,"HTTPSConnectionPool(host='scielo.org.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57facca0>, 'Connection to scielo.org.mx timed out. (connect timeout=2)'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scielo.org.pe,"HTTPSConnectionPool(host='scielo.org.pe', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58343160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.pe', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57fcb250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.org.za,"HTTPSConnectionPool(host='scielo.org.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57fd8a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.org.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58048580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scielo.sa.cr,"HTTPSConnectionPool(host='scielo.sa.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5811ceb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scielo.sa.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58048670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scimath.org,"HTTPSConnectionPool(host='scimath.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scimath.org' doesn't match 'www.scimath.org'"")))","HTTPSConnectionPool(host='scimath.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scimath.org' doesn't match 'www.scimath.org'"")))"
scjn.gob.mx,"HTTPSConnectionPool(host='scjn.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58366940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scjn.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57f94c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
scoilnet.ie,"HTTPSConnectionPool(host='scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.scoilnet.ie', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
scotiabank.com.uy,"HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))","HTTPSConnectionPool(host='scotiabank.com.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'scotiabank.com.uy' doesn't match either of 'a248.e.akamai.net', '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaihd.net', '*.akamaized-staging.net'"")))"
scotiabankcolpatria.com,"HTTPSConnectionPool(host='scotiabankcolpatria.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a580bc460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='scotiabankcolpatria.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58004fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
screenrant.com,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
scv.si,"HTTPSConnectionPool(host='www.scv.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.scv.si', port=443): Read timed out. (read timeout=2)"
sdetmi.com,"HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sdetmi.com', port=443): Read timed out. (read timeout=2)"
sdp.gov.co,"HTTPSConnectionPool(host='sdp.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57f5c1f0>, 'Connection to sdp.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sdp.gov.co', port=80): Read timed out. (read timeout=2)"
sears.com.mx,"HTTPSConnectionPool(host='sears.com.mx', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sears.com.mx', port=80): Read timed out. (read timeout=2)"
seattletimes.com,"HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.seattletimes.com', port=443): Read timed out. (read timeout=2)"
sec.or.th,"HTTPSConnectionPool(host='sec.or.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a583592e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sec.or.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57ee9c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
seedly.sg,"HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='seedly.sg', port=443): Read timed out. (read timeout=2)"
seen.lk,"HTTPSConnectionPool(host='seen.lk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.seen.lk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
seguridadpublica.go.cr,"HTTPSConnectionPool(host='seguridadpublica.go.cr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58077070>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='seguridadpublica.go.cr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5839fc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sej.co.jp,"HTTPSConnectionPool(host='sej.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57ec8af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sej.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57f94be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
selangor.gov.my,"HTTPSConnectionPool(host='selangor.gov.my', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57fdd7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='selangor.gov.my', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57facdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
semarnat.gob.mx,"HTTPSConnectionPool(host='semarnat.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5804b6d0>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='semarnat.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a580c6ee0>, 'Connection to semarnat.gob.mx timed out. (connect timeout=2)'))"
semmelweis.hu,"HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='semmelweis.hu', port=443): Read timed out. (read timeout=2)"
sena.edu.co,"HTTPSConnectionPool(host='sena.edu.co', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='sena.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a58139be0>, 'Connection to sena.edu.co timed out. (connect timeout=2)'))"
senac.br,"HTTPSConnectionPool(host='senac.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57e9e910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senac.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a5827e8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senado.gob.mx,"HTTPSConnectionPool(host='senado.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57f4c460>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senado.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58027970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
senate.go.th,"HTTPSConnectionPool(host='senate.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582ed130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='senate.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a58343100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sep.gob.mx,"HTTPSConnectionPool(host='sep.gob.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57f2b400>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sep.gob.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a586f7610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sephora.com,"HTTPSConnectionPool(host='www.sephora.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.com', port=443): Read timed out. (read timeout=2)"
sephora.fr,"HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.fr', port=443): Read timed out. (read timeout=2)"
sephora.pl,"HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.pl', port=443): Read timed out. (read timeout=2)"
sephora.sa,"HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sephora.sa', port=443): Read timed out. (read timeout=2)"
sepyc.gob.mx,"HTTPSConnectionPool(host='sepyc.gob.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57eaa400>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sepyc.gob.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a5806c940>, 'Connection to sepyc.gob.mx timed out. (connect timeout=2)'))"
sernac.cl,"HTTPSConnectionPool(host='sernac.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57c00fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sernac.cl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57f2b340>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
servina.net,"HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='servina.net', port=443): Read timed out. (read timeout=2)"
set.edu.br,"HTTPSConnectionPool(host='set.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a5804bbb0>, 'Connection to set.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='set.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a57d8e070>, 'Connection to set.edu.br timed out. (connect timeout=2)'))"
sevenspeed.it,Exceeded 30 redirects.,Exceeded 30 redirects.
sfatulmedicului.ro,"HTTPSConnectionPool(host='www.sfatulmedicului.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sfatulmedicului.ro', port=443): Read timed out. (read timeout=2)"
sgg.gov.ma,"HTTPSConnectionPool(host='sgg.gov.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a55dc69a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sgg.gov.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a55ef1430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sggw.pl,"HTTPSConnectionPool(host='sggw.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='sggw.edu.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sgk.gov.tr,"HTTPSConnectionPool(host='sgk.gov.tr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a582b98b0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.sgk.gov.tr', port=80): Read timed out. (read timeout=2)"
sharp.co.jp,"HTTPSConnectionPool(host='sharp.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a580dcdf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sharp.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a55ddd040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
shd.gov.co,"HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='shd.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
shop.by,"HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shop.by', port=443): Read timed out. (read timeout=2)"
shopbot.ca,"HTTPSConnectionPool(host='shopbot.ca', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a580a35e0>, 'Connection to shopbot.ca timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shopbot.ca', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a57ee96a0>, 'Connection to shopbot.ca timed out. (connect timeout=2)'))"
shopbot.com.au,"HTTPSConnectionPool(host='shopbot.com.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a56fd3250>, 'Connection to shopbot.com.au timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shopbot.com.au', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a58004af0>, 'Connection to shopbot.com.au timed out. (connect timeout=2)'))"
shopix.cl,"HTTPSConnectionPool(host='shopix.cl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a57c4b550>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='shopix.cl', port=80): Read timed out. (read timeout=2)"
shopix.com.ar,"HTTPSConnectionPool(host='shopix.com.ar', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shopix.com.ar', port=443): Read timed out. (read timeout=2)"
shoppaloss.se,"HTTPSConnectionPool(host='shoppaloss.se', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57c077c0>, 'Connection to shoppaloss.se timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shoppaloss.se', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a55ec5310>: Failed to establish a new connection: [Errno 113] No route to host'))"
shopsy.pk,"HTTPSConnectionPool(host='shopsy.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='shopsy.pk', port=443): Read timed out. (read timeout=2)"
shoptime.com.br,"HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.shoptime.com.br', port=443): Read timed out. (read timeout=2)"
showcase-tv.com,"HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))","HTTPSConnectionPool(host='showcase-tv.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'showcase-tv.com' doesn't match either of 'www.showcase-tv.com', 'bitwave.showcase-tv.com', 'financial.showcase-tv.com'"")))"
shufersal.co.il,"HTTPSConnectionPool(host='shufersal.co.il', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57ca3700>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))","HTTPConnectionPool(host='shufersal.co.il', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a57d2dc10>, 'Connection to shufersal.co.il timed out. (connect timeout=2)'))"
siauliai.lt,"HTTPSConnectionPool(host='siauliai.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.siauliai.lt', port=443): Read timed out. (read timeout=2)"
siauliuraj.lt,"HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))","HTTPSConnectionPool(host='siauliuraj.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'siauliuraj.lt' doesn't match either of 'old.siauliuraj.lt', 'www.siauliuraj.lt'"")))"
sib.gob.gt,"HTTPSConnectionPool(host='sib.gob.gt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a5866c1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sib.gob.gt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57c10670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
siboif.gob.ni,"HTTPSConnectionPool(host='siboif.gob.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a583dc790>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='siboif.gob.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57c4bf40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sic.gov.co,"HTTPSConnectionPool(host='sic.gov.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a56fea940>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sic.gov.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a5824c700>, 'Connection to sic.gov.co timed out. (connect timeout=2)'))"
sicad.gov.tn,"HTTPSConnectionPool(host='sicad.gov.tn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a58154bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sicad.gov.tn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a57c00970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
sieviesuklubs.lv,"HTTPSConnectionPool(host='sieviesuklubs.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.sieviesuklubs.lv', port=80): Read timed out. (read timeout=2)"
sii.cl,"HTTPSConnectionPool(host='sii.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a581c6940>, 'Connection to sii.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='sii.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a55e74760>, 'Connection to sii.cl timed out. (connect timeout=2)'))"
sik.si,"HTTPSConnectionPool(host='sik.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2a56fdd6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='sik.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2a55d82ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
singaporeair.com,"HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.singaporeair.com', port=443): Read timed out. (read timeout=2)"
singaporelegaladvice.com,"HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporelegaladvice.com', port=443): Read timed out. (read timeout=2)"
singaporemotherhood.com,"HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='singaporemotherhood.com', port=443): Read timed out. (read timeout=2)"
sirvintos.lt,"HTTPSConnectionPool(host='sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.sirvintos.lt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sis.gov.eg,"HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='sis.gov.eg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
sistory.si,"HTTPSConnectionPool(host='sistory.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a57cdc9a0>, 'Connection to sistory.si timed out. (connect timeout=2)'))","HTTPSConnectionPool(host='sistory.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2a570391c0>, 'Connection to sistory.si timed out. (connect timeout=2)'))"
sitemercado.com.br,"HTTPSConnectionPool(host='www.sitemercado.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.sitemercado.com.br', port=443): Read timed out. (read timeout=2)"
sitfit.si,"HTTPSConnectionPool(host='sitfit.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='sitfit.si', port=443): Read timed out. (read timeout=2)"
