trakya.edu.tr,"HTTPSConnectionPool(host='trakya.edu.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e495c70a0>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='trakya.edu.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e48d041f0>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))"
trans-suite.jp,"HTTPSConnectionPool(host='trans-suite.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e48fc9ca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='trans-suite.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4870bd30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
transitlink.com.sg,"HTTPSConnectionPool(host='transitlink.com.sg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'transitlink.com.sg' doesn't match either of 'tlwebmail.transitlink.com.sg', 'www.tlwebmail.transitlink.com.sg', 'lb.transitlink.com.sg', 'www.transitlink.com.sg', 'autodiscover.transitlink.com.sg', 'failover.transitlink.com.sg'"")))","HTTPConnectionPool(host='transitlink.com.sg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e48541fa0>, 'Connection to transitlink.com.sg timed out. (connect timeout=2)'))"
translate.ru,"HTTPSConnectionPool(host='translate.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.translate.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
transparencia.org.ve,"HTTPSConnectionPool(host='transparencia.org.ve', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='transparencia.org.ve', port=443): Read timed out. (read timeout=2)"
transportecarretero.com.uy,"HTTPSConnectionPool(host='www.transportecarretero.com.uy', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.transportecarretero.com.uy', port=443): Read timed out. (read timeout=2)"
treasury.go.th,"HTTPSConnectionPool(host='treasury.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e485332b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='treasury.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e479bdd00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
treasury.gov.za,"HTTPSConnectionPool(host='treasury.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4823cb20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='treasury.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e47a342e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
trekpleister.nl,"HTTPSConnectionPool(host='trekpleister.nl', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='trekpleister.nl', port=80): Read timed out. (read timeout=2)"
triangletechhire.com,"HTTPSConnectionPool(host='triangletechhire.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e46dda490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='triangletechhire.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e46779490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tribune.bg,"HTTPSConnectionPool(host='tribune.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tribune.bg', port=443): Read timed out. (read timeout=2)"
trithuccuocsong.vn,"HTTPSConnectionPool(host='trithuccuocsong.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='trithuccuocsong.vn', port=443): Read timed out. (read timeout=2)"
triton.com.ro,"HTTPSConnectionPool(host='triton.com.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.triton.com.ro', port=443): Read timed out. (read timeout=2)"
trovaperme.it,"HTTPSConnectionPool(host='www.trovaperme.it', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.trovaperme.it', port=443): Read timed out. (read timeout=2)"
trudipravo.bg,"HTTPSConnectionPool(host='trudipravo.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))","HTTPConnectionPool(host='trudipravo.bg', port=80): Read timed out. (read timeout=2)"
trudvsem.ru,"HTTPSConnectionPool(host='trudvsem.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='trudvsem.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
truecorp.co.th,"HTTPSConnectionPool(host='truecorp.co.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e4596b610>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='truecorp.co.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e459ad670>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))"
trueid.net,"HTTPSConnectionPool(host='home.trueid.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='home.trueid.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
tryit.lk,"HTTPSConnectionPool(host='tryit.lk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tryit.lk', port=80): Read timed out. (read timeout=2)"
tshwane.gov.za,"HTTPSConnectionPool(host='tshwane.gov.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e476233d0>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tshwane.gov.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e47dfa610>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))"
tsk.sk,"HTTPSConnectionPool(host='tsk.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='tsk.sk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
tsu.ac.th,"HTTPSConnectionPool(host='tsu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e452c16d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='tsu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e45509190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
tsukuba.ac.jp,"HTTPSConnectionPool(host='tsukuba.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e46fd7160>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='tsukuba.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e489782e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
tsutaya.co.jp,"HTTPSConnectionPool(host='tsutaya.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e470a3f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='tsutaya.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e46dc5e80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ttja.ee,"HTTPSConnectionPool(host='ttja.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e4694fe50>, 'Connection to ttja.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ttja.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e480abe50>, 'Connection to ttja.ee timed out. (connect timeout=2)'))"
tucarro.com.co,"HTTPSConnectionPool(host='tucarro.com.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e43392070>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tucarro.com.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e480e1c10>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))"
tui.co.uk,"HTTPSConnectionPool(host='tui.co.uk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tui.co.uk', port=80): Read timed out. (read timeout=2)"
tuiasi.ro,"HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)"
tunisie-annonce.com,"HTTPSConnectionPool(host='tunisie-annonce.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e43473f40>, 'Connection to tunisie-annonce.com timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tunisie-annonce.com', port=80): Read timed out. (read timeout=2)"
tunivisions.net,"HTTPSConnectionPool(host='tunivisions.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e471ebe80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='tunivisions.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e47e5a520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
turess.com,"HTTPSConnectionPool(host='www.turess.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.turess.com', port=443): Read timed out. (read timeout=2)"
turismo.gob.ec,"HTTPSConnectionPool(host='turismo.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'turismo.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
turkcebelesmp3indir.com,"HTTPSConnectionPool(host='turkcebelesmp3indir.com', port=443): Read timed out.","HTTPSConnectionPool(host='turkcebelesmp3indir.com', port=443): Read timed out."
turkcell.com.tr,"HTTPSConnectionPool(host='turkcell.com.tr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='turkcell.com.tr', port=80): Read timed out. (read timeout=2)"
turkishairlines.com,"HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)"
tut.by,"HTTPSConnectionPool(host='tut.by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e443942e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='tut.by', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e48a1e9d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
tvambienti.si,"HTTPSConnectionPool(host='www.tvambienti.si', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tvambienti.si', port=443): Read timed out. (read timeout=2)"
tvmost.info,"HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)"
u-szeged.hu,"HTTPSConnectionPool(host='u-szeged.hu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e49066070>, 'Connection to u-szeged.hu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='u-szeged.hu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e436e6340>, 'Connection to u-szeged.hu timed out. (connect timeout=2)'))"
u-tokyo.ac.jp,"HTTPSConnectionPool(host='u-tokyo.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e443c1a00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='u-tokyo.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e482a83d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
u.ae,"HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)"
ua.es,"HTTPSConnectionPool(host='ua.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e470b5670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ua.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e48541a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ua.pt,"HTTPSConnectionPool(host='ua.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e46c79070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ua.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e48172a30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uabc.mx,"HTTPSConnectionPool(host='uabc.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4706f5b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uabc.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e481214f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uacj.mx,"HTTPSConnectionPool(host='uacj.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e48ba1040>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uacj.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4566bca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uaemex.mx,"HTTPSConnectionPool(host='uaemex.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4525c940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uaemex.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e426026a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uaic.ro,"HTTPSConnectionPool(host='uaic.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uaic.ro', port=443): Read timed out. (read timeout=2)"
uainfo.com,"HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)"
ual.es,"HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))","HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))"
uam.edu.ni,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
uam.mx,"HTTPSConnectionPool(host='uam.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e41cc5f40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uam.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4618a1c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uanl.mx,"HTTPSConnectionPool(host='uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uasb.edu.ec,"HTTPSConnectionPool(host='uasb.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPConnectionPool(host='uasb.edu.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e49246250>, 'Connection to uasb.edu.ec timed out. (connect timeout=2)'))"
uaslp.mx,"HTTPSConnectionPool(host='uaslp.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e473835b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uaslp.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e454cd790>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ub.ac.id,"HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out. (read timeout=2)"
ubi.pt,"HTTPSConnectionPool(host='ubi.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e40ab3f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ubi.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e458ad760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ubu.ac.th,"HTTPSConnectionPool(host='ubu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4164d0a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ubu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e48d29850>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uc.edu.ve,"HTTPSConnectionPool(host='uc.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4678f400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uc.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4551b7c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uca.edu.ni,"HTTPSConnectionPool(host='uca.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4381a8b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uca.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4539f1f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ucc.ie,"HTTPSConnectionPool(host='ucc.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e402ebd30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucc.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e46be99a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ucd.ie,"HTTPSConnectionPool(host='ucd.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4661d3d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucd.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e47a3bf10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uce.edu.ec,"HTTPSConnectionPool(host='uce.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uce.edu.ec', port=443): Read timed out. (read timeout=2)"
ucg.ac.me,"HTTPSConnectionPool(host='ucg.ac.me', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e44e7afa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='ucg.ac.me', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e454d9df0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
uciteljska.net,"HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
ucla.edu.ve,"HTTPSConnectionPool(host='ucla.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4769fca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucla.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e43891910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ucol.mx,"HTTPSConnectionPool(host='ucol.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e443c1d30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucol.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e483e7b80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ucuenca.edu.ec,"HTTPSConnectionPool(host='ucuenca.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e455c7a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucuenca.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e40e00580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ucv.ro,"HTTPSConnectionPool(host='ucv.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e3feb4940>, 'Connection to ucv.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ucv.ro', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e41088bb0>, 'Connection to ucv.ro timed out. (connect timeout=2)'))"
ucv.ve,"HTTPSConnectionPool(host='ucv.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e44f17730>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ucv.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e430c6340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
udb.edu.sv,"HTTPSConnectionPool(host='udb.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4843e9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='udb.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e46d21d60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
udesc.br,"HTTPSConnectionPool(host='udesc.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.udesc.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
udg.mx,"HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
udiconcalabria.org,"HTTPSConnectionPool(host='www.udiconcalabria.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.udiconcalabria.org', port=443): Read timed out. (read timeout=2)"
udp.cl,"HTTPSConnectionPool(host='udp.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e461bbf40>, 'Connection to udp.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='udp.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e4518b910>, 'Connection to udp.cl timed out. (connect timeout=2)'))"
udv.edu.gt,"HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uees.edu.ec,"HTTPSConnectionPool(host='uees.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.uees.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
uem.br,"HTTPSConnectionPool(host='uem.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e4612dd60>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='uem.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e42fbd820>: Failed to establish a new connection: [Errno 113] No route to host'))"
uerj.br,"HTTPSConnectionPool(host='uerj.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e40176220>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uerj.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e451d2430>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ues.edu.sv,"HTTPSConnectionPool(host='ues.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e432ede20>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ues.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4270ad30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
uesiglo21.edu.ar,"HTTPSConnectionPool(host='uesiglo21.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e48fb48b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uesiglo21.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e450004c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uespi.br,"HTTPSConnectionPool(host='uespi.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e46fd7a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uespi.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e43c67c40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uexternado.edu.co,"HTTPSConnectionPool(host='uexternado.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e46ccb610>, 'Connection to uexternado.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uexternado.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e46a04af0>, 'Connection to uexternado.edu.co timed out. (connect timeout=2)'))"
ufma.br,"HTTPSConnectionPool(host='ufma.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e44e7ad30>, 'Connection to ufma.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufma.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e44394280>, 'Connection to ufma.br timed out. (connect timeout=2)'))"
ufmt.br,"HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)"
ufp.pt,"HTTPSConnectionPool(host='ufp.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e3fe9f040>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ufp.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e487e5370>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ufpe.br,"HTTPSConnectionPool(host='ufpe.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e3feda3d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ufpe.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e3fb6d9d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ufrj.br,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ufs.ac.za,"HTTPSConnectionPool(host='ufs.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e460c0610>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufs.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e4928a6d0>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))"
ufu.br,"HTTPSConnectionPool(host='ufu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e3faa8dc0>, 'Connection to ufu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e40151e80>, 'Connection to ufu.br timed out. (connect timeout=2)'))"
ug.edu.ec,"HTTPSConnectionPool(host='ug.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e46b04dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ug.edu.ec', port=80): Read timed out. (read timeout=2)"
ugto.mx,"HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uhaena.com,"HTTPSConnectionPool(host='uhaena.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e471237c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uhaena.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e3fc31cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
ui.ac.id,"HTTPSConnectionPool(host='ui.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ui.ac.id', port=443): Read timed out. (read timeout=2)"
uin-suska.ac.id,"HTTPSConnectionPool(host='uin-suska.ac.id', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8e4729f880>, 'Connection to uin-suska.ac.id timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uin-suska.ac.id', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8e47472eb0>, 'Connection to uin-suska.ac.id timed out. (connect timeout=2)'))"
uinsgd.ac.id,"HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)"
uji.es,"HTTPSConnectionPool(host='uji.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e48a5f5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='uji.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8e4330e2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ukazatelite.com,"HTTPSConnectionPool(host='ukazatelite.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ukazatelite.com', port=443): Read timed out. (read timeout=2)"
uky.edu,"HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))","HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))"
ukzinios.lt,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","HTTPSConnectionPool(host='www.ukzinios.lt', port=443): Read timed out. (read timeout=2)"
