trakya.edu.tr,"HTTPSConnectionPool(host='trakya.edu.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bf547790>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='trakya.edu.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4be9a4af0>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))"
trans-suite.jp,"HTTPSConnectionPool(host='trans-suite.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4becd5d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='trans-suite.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be503040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
transitlink.com.sg,"HTTPSConnectionPool(host='transitlink.com.sg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'transitlink.com.sg' doesn't match either of 'tlwebmail.transitlink.com.sg', 'www.tlwebmail.transitlink.com.sg', 'lb.transitlink.com.sg', 'www.transitlink.com.sg', 'autodiscover.transitlink.com.sg', 'failover.transitlink.com.sg'"")))","HTTPConnectionPool(host='transitlink.com.sg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4be337ca0>, 'Connection to transitlink.com.sg timed out. (connect timeout=2)'))"
travelingyuk.com,"HTTPSConnectionPool(host='travelingyuk.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='travelingyuk.com', port=443): Read timed out. (read timeout=2)"
treasury.go.th,"HTTPSConnectionPool(host='treasury.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4beb83370>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='treasury.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bd4c82b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
treasury.gov.za,"HTTPSConnectionPool(host='treasury.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bc009f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='treasury.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bdab1490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
trekpleister.nl,"HTTPSConnectionPool(host='trekpleister.nl', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='trekpleister.nl', port=80): Read timed out. (read timeout=2)"
treningsforum.no,"HTTPSConnectionPool(host='treningsforum.no', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='treningsforum.no', port=80): Read timed out. (read timeout=2)"
triangletechhire.com,"HTTPSConnectionPool(host='triangletechhire.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bcfdc160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='triangletechhire.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bbd36d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tribune.bg,"HTTPSConnectionPool(host='tribune.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tribune.bg', port=443): Read timed out. (read timeout=2)"
tribune.com.pk,"HTTPSConnectionPool(host='tribune.com.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tribune.com.pk', port=443): Read timed out. (read timeout=2)"
trithuccuocsong.vn,"HTTPSConnectionPool(host='trithuccuocsong.vn', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='trithuccuocsong.vn', port=443): Read timed out. (read timeout=2)"
triton.com.ro,"HTTPSConnectionPool(host='triton.com.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.triton.com.ro', port=443): Read timed out. (read timeout=2)"
truck2hand.com,"HTTPSConnectionPool(host='www.truck2hand.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.truck2hand.com', port=443): Read timed out. (read timeout=2)"
truecorp.co.th,"HTTPSConnectionPool(host='truecorp.co.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bd5fd970>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='truecorp.co.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4b9080160>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))"
tryit.lk,"HTTPSConnectionPool(host='tryit.lk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tryit.lk', port=80): Read timed out. (read timeout=2)"
tshwane.gov.za,"HTTPSConnectionPool(host='tshwane.gov.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bd161c10>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tshwane.gov.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4bc7c7f70>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))"
tsu.ac.th,"HTTPSConnectionPool(host='tsu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4beadc7f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='tsu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bb6deac0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
tsukuba.ac.jp,"HTTPSConnectionPool(host='tsukuba.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b70effd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tsukuba.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b90fca60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tsutaya.co.jp,"HTTPSConnectionPool(host='tsutaya.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b6b990a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tsutaya.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be6dea90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tucarro.com.co,"HTTPSConnectionPool(host='tucarro.com.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4b5c15820>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tucarro.com.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4b64c1040>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))"
tui.co.uk,"HTTPSConnectionPool(host='tui.co.uk', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tui.co.uk', port=80): Read timed out. (read timeout=2)"
tuiasi.ro,"HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)"
tunivisions.net,"HTTPSConnectionPool(host='tunivisions.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bb0a6340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tunivisions.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b5357670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
turismo.gob.ec,"HTTPSConnectionPool(host='turismo.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'turismo.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
turkcebelesmp3indir.com,"HTTPSConnectionPool(host='turkcebelesmp3indir.com', port=443): Read timed out.","HTTPSConnectionPool(host='turkcebelesmp3indir.com', port=443): Read timed out."
turkcell.com.tr,"HTTPSConnectionPool(host='turkcell.com.tr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='turkcell.com.tr', port=80): Read timed out. (read timeout=2)"
turkishairlines.com,"HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)"
tut.by,"HTTPSConnectionPool(host='tut.by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4be9cc5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='tut.by', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bf12da60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
tuugo.co.ni,"HTTPSConnectionPool(host='tuugo.co.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bcc719d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tuugo.co.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b9d74b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tvmost.info,"HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)"
tvr.ro,"HTTPSConnectionPool(host='tvr.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bc06a310>, 'Connection to tvr.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='www.tvr.ro', port=80): Read timed out. (read timeout=2)"
tvsur.co.cr,"HTTPSConnectionPool(host='www.tvsur.co.cr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='tvsur.co.cr', port=80): Read timed out. (read timeout=2)"
u-tokyo.ac.jp,"HTTPSConnectionPool(host='u-tokyo.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bb5fe940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='u-tokyo.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b8c41490>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
u.ae,"HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)"
ua.es,"HTTPSConnectionPool(host='ua.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bdef0dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ua.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b5b29370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ua.pt,"HTTPSConnectionPool(host='ua.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b5ed5850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ua.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b5546970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uabc.mx,"HTTPSConnectionPool(host='uabc.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4be527220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uabc.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b5e633a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uacj.mx,"HTTPSConnectionPool(host='uacj.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bd40e1f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uacj.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be4a0d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uaemex.mx,"HTTPSConnectionPool(host='uaemex.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b94f3880>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uaemex.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be7db550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uaic.ro,"HTTPSConnectionPool(host='uaic.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uaic.ro', port=443): Read timed out. (read timeout=2)"
uainfo.com,"HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)"
ual.es,"HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))","HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))"
uam.edu.ni,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
uam.mx,"HTTPSConnectionPool(host='uam.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bbe9bd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uam.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b8ed59d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uanl.mx,"HTTPSConnectionPool(host='uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uasb.edu.ec,"HTTPSConnectionPool(host='uasb.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='uasb.edu.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4be094ac0>, 'Connection to uasb.edu.ec timed out. (connect timeout=2)'))"
uaslp.mx,"HTTPSConnectionPool(host='uaslp.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4ba968520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uaslp.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bdbc35b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ub.ac.id,"HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out. (read timeout=2)"
ubi.pt,"HTTPSConnectionPool(host='ubi.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4be6de520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ubi.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be85da60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ubu.ac.th,"HTTPSConnectionPool(host='ubu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b65ec7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ubu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bb5e93d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uc.edu.ve,"HTTPSConnectionPool(host='uc.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4be688eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uc.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bc4f8760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uca.edu.ni,"HTTPSConnectionPool(host='uca.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bde06e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uca.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4ba968820>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucatolica.edu.co,"HTTPSConnectionPool(host='ucatolica.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4be379880>, 'Connection to ucatolica.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ucatolica.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4b50a7460>, 'Connection to ucatolica.edu.co timed out. (connect timeout=2)'))"
ucc.ie,"HTTPSConnectionPool(host='ucc.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bcd5b730>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucc.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bed7f910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucd.ie,"HTTPSConnectionPool(host='ucd.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b65f6ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucd.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be0c8cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uciteljska.net,"HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ucla.edu.ve,"HTTPSConnectionPool(host='ucla.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b9c699a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucla.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b74f78e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucn.cl,"HTTPSConnectionPool(host='ucn.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ucn.cl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ucol.mx,"HTTPSConnectionPool(host='ucol.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bd68a340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucol.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bb6de6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucuenca.edu.ec,"HTTPSConnectionPool(host='ucuenca.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b510f970>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucuenca.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bd980ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucv.ro,"HTTPSConnectionPool(host='ucv.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4b4f9d100>, 'Connection to ucv.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ucv.ro', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4bd37bf10>, 'Connection to ucv.ro timed out. (connect timeout=2)'))"
ucv.ve,"HTTPSConnectionPool(host='ucv.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bb9bd3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucv.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b53836a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
udb.edu.sv,"HTTPSConnectionPool(host='udb.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b510fc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='udb.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b9da11f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
udg.mx,"HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
udiconcalabria.org,"HTTPSConnectionPool(host='www.udiconcalabria.org', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.udiconcalabria.org', port=80): Read timed out. (read timeout=2)"
udp.cl,"HTTPSConnectionPool(host='udp.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bd5eb850>, 'Connection to udp.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='udp.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4b4ffb250>, 'Connection to udp.cl timed out. (connect timeout=2)'))"
udv.edu.gt,"HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uem.br,"HTTPSConnectionPool(host='uem.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4be037280>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='uem.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4be8db700>: Failed to establish a new connection: [Errno 113] No route to host'))"
uerj.br,"HTTPSConnectionPool(host='uerj.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bf1d4f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uerj.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bde063a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ues.edu.sv,"HTTPSConnectionPool(host='ues.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bcdb6160>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ues.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bddb49d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
uesiglo21.edu.ar,"HTTPSConnectionPool(host='uesiglo21.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b9be2b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uesiglo21.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bcc71700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uespi.br,"HTTPSConnectionPool(host='uespi.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4bd3ab850>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uespi.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4beefa460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uexternado.edu.co,"HTTPSConnectionPool(host='uexternado.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bcf50250>, 'Connection to uexternado.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uexternado.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4becd5880>, 'Connection to uexternado.edu.co timed out. (connect timeout=2)'))"
ufam.edu.br,"HTTPSConnectionPool(host='ufam.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4be193d60>, 'Connection to ufam.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufam.edu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4be6a9df0>, 'Connection to ufam.edu.br timed out. (connect timeout=2)'))"
ufma.br,"HTTPSConnectionPool(host='ufma.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4b988f670>, 'Connection to ufma.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufma.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4baefb910>, 'Connection to ufma.br timed out. (connect timeout=2)'))"
ufmt.br,"HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)"
ufp.pt,"HTTPSConnectionPool(host='ufp.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4ba41db50>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ufp.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b50fd400>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ufpe.br,"HTTPSConnectionPool(host='ufpe.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b510f760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ufpe.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bce2c400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ufrj.br,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ufs.ac.za,"HTTPSConnectionPool(host='ufs.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4bd195280>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufs.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4ba4856d0>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))"
ufu.br,"HTTPSConnectionPool(host='ufu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4b4ce42b0>, 'Connection to ufu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa4b4e1afd0>, 'Connection to ufu.br timed out. (connect timeout=2)'))"
ug.edu.ec,"HTTPSConnectionPool(host='ug.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b4e71940>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ug.edu.ec', port=80): Read timed out. (read timeout=2)"
ugto.mx,"HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uhaena.com,"HTTPSConnectionPool(host='uhaena.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4b654bcd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uhaena.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b4f37c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ui.ac.id,"HTTPSConnectionPool(host='ui.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ui.ac.id', port=443): Read timed out. (read timeout=2)"
uinsgd.ac.id,"HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)"
uji.es,"HTTPSConnectionPool(host='uji.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4befe2790>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='uji.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4b537e310>: Failed to establish a new connection: [Errno 111] Connection refused'))"
uky.edu,"HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))","HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))"
