trakya.edu.tr,"HTTPSConnectionPool(host='trakya.edu.tr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e08eea0d0>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))","HTTPConnectionPool(host='trakya.edu.tr', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08df69d0>, 'Connection to trakya.edu.tr timed out. (connect timeout=2)'))"
transitlink.com.sg,"HTTPSConnectionPool(host='transitlink.com.sg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'transitlink.com.sg' doesn't match either of 'tlwebmail.transitlink.com.sg', 'www.tlwebmail.transitlink.com.sg', 'lb.transitlink.com.sg', 'www.transitlink.com.sg', 'autodiscover.transitlink.com.sg', 'failover.transitlink.com.sg'"")))","HTTPConnectionPool(host='transitlink.com.sg', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08caf910>, 'Connection to transitlink.com.sg timed out. (connect timeout=2)'))"
transparenciaactiva.gob.sv,"HTTPSConnectionPool(host='transparenciaactiva.gob.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08df6ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='transparenciaactiva.gob.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08bf6100>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
transportal.com.br,"HTTPSConnectionPool(host='www.transportal.com.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.transportal.com.br', port=443): Read timed out. (read timeout=2)"
transportecarretero.com.uy,"HTTPSConnectionPool(host='www.transportecarretero.com.uy', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.transportecarretero.com.uy', port=443): Read timed out. (read timeout=2)"
traveloka.com,"HTTPSConnectionPool(host='www.traveloka.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.traveloka.com', port=443): Read timed out. (read timeout=2)"
treasury.go.th,"HTTPSConnectionPool(host='treasury.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08b243d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='treasury.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08b880a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
treasury.gov.za,"HTTPSConnectionPool(host='treasury.gov.za', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08b88550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='treasury.gov.za', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08b99370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
trekpleister.nl,"HTTPSConnectionPool(host='trekpleister.nl', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='trekpleister.nl', port=80): Read timed out. (read timeout=2)"
trescruces.com.uy,"HTTPSConnectionPool(host='trescruces.com.uy', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='trescruces.com.uy', port=443): Read timed out. (read timeout=2)"
tribune.com.pk,"HTTPSConnectionPool(host='tribune.com.pk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tribune.com.pk', port=443): Read timed out. (read timeout=2)"
triton.com.ro,"HTTPSConnectionPool(host='triton.com.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.triton.com.ro', port=443): Read timed out. (read timeout=2)"
truecorp.co.th,"HTTPSConnectionPool(host='truecorp.co.th', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e08913eb0>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))","HTTPConnectionPool(host='truecorp.co.th', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e085f5a00>, 'Connection to truecorp.co.th timed out. (connect timeout=2)'))"
tshwane.gov.za,"HTTPSConnectionPool(host='tshwane.gov.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e087cf9a0>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tshwane.gov.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08e04df0>, 'Connection to tshwane.gov.za timed out. (connect timeout=2)'))"
tsn.ca,"HTTPSConnectionPool(host='www.tsn.ca', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tsn.ca', port=443): Read timed out. (read timeout=2)"
tsukuba.ac.jp,"HTTPSConnectionPool(host='tsukuba.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0864a940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tsukuba.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e088b1df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tsutaya.co.jp,"HTTPSConnectionPool(host='tsutaya.co.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e086da250>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tsutaya.co.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0897fdc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tu-berlin.de,"HTTPSConnectionPool(host='tu-berlin.de', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e08704e50>, 'Connection to tu-berlin.de timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tu-berlin.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08bf6370>, 'Connection to tu-berlin.de timed out. (connect timeout=2)'))"
tucarro.com.co,"HTTPSConnectionPool(host='tucarro.com.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e086b4760>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='tucarro.com.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08aa0ee0>, 'Connection to tucarro.com.co timed out. (connect timeout=2)'))"
tuiasi.ro,"HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tuiasi.ro', port=443): Read timed out. (read timeout=2)"
tuning.bg,"HTTPSConnectionPool(host='tuning.bg', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08136e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='www.tuning.bg', port=80): Read timed out. (read timeout=2)"
tunivisions.net,"HTTPSConnectionPool(host='tunivisions.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08668bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tunivisions.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e085214c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
turismo.gob.ec,"HTTPSConnectionPool(host='turismo.gob.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'turismo.gob.ec' doesn't match either of 'www.agricultura.gob.ec', 'agricultura.gob.ec'"")))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
turistickyatlas.cz,"HTTPSConnectionPool(host='turistickyatlas.cz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='turistickyatlas.cz', port=443): Read timed out. (read timeout=2)"
turisticna-zveza.si,"HTTPSConnectionPool(host='turisticna-zveza.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e086e8eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='turisticna-zveza.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08b7b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
turkcebilgi.com,"HTTPSConnectionPool(host='www.turkcebilgi.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.turkcebilgi.com', port=443): Read timed out. (read timeout=2)"
turkcell.com.tr,"HTTPSConnectionPool(host='turkcell.com.tr', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='turkcell.com.tr', port=80): Read timed out. (read timeout=2)"
turkishairlines.com,"HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.turkishairlines.com', port=443): Read timed out. (read timeout=2)"
tut.by,"HTTPSConnectionPool(host='tut.by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e088c12e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='tut.by', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08911be0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
tuugo.co.ni,"HTTPSConnectionPool(host='tuugo.co.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0857de50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='tuugo.co.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0872d640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
tventas.com,"HTTPSConnectionPool(host='www.tventas.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.tventas.com', port=443): Read timed out. (read timeout=2)"
tvmost.info,"HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='tvmost.info', port=443): Read timed out. (read timeout=2)"
u-tokyo.ac.jp,"HTTPSConnectionPool(host='u-tokyo.ac.jp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e089b7cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='u-tokyo.ac.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e081332e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
u.ae,"HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='u.ae', port=443): Read timed out. (read timeout=2)"
ua.es,"HTTPSConnectionPool(host='ua.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08b7bf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ua.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08088310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ua.pt,"HTTPSConnectionPool(host='ua.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e089ff5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ua.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08863d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uabc.mx,"HTTPSConnectionPool(host='uabc.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08777220>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uabc.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e087c7fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uacj.mx,"HTTPSConnectionPool(host='uacj.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0890a7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uacj.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e086e8310>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uaemex.mx,"HTTPSConnectionPool(host='uaemex.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e089589a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uaemex.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08883be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uaic.ro,"HTTPSConnectionPool(host='uaic.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uaic.ro', port=443): Read timed out. (read timeout=2)"
uainfo.com,"HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uainfo.com', port=443): Read timed out. (read timeout=2)"
ual.es,"HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))","HTTPSConnectionPool(host='ual.es', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ual.es' doesn't match either of 'www.ual.es', 'ualcms.ual.es'"")))"
uam.edu.ni,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
uam.mx,"HTTPSConnectionPool(host='uam.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0860d4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uam.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e082ecf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uamulet.com,"HTTPSConnectionPool(host='uamulet.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='uamulet.com', port=80): Read timed out. (read timeout=2)"
uanl.mx,"HTTPSConnectionPool(host='uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uanl.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uasb.edu.ec,"HTTPSConnectionPool(host='uasb.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPConnectionPool(host='uasb.edu.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08afc2b0>, 'Connection to uasb.edu.ec timed out. (connect timeout=2)'))"
uaslp.mx,"HTTPSConnectionPool(host='uaslp.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0818b640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uaslp.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08abb2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ub.ac.id,"HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out.","HTTPSConnectionPool(host='ub.ac.id', port=443): Read timed out."
ubi.pt,"HTTPSConnectionPool(host='ubi.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e083ef4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ubi.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e089b7c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ubica.ec,"HTTPSConnectionPool(host='ubica.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ubica.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ubu.ac.th,"HTTPSConnectionPool(host='ubu.ac.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e09431280>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ubu.ac.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0894f700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uc.edu.ve,"HTTPSConnectionPool(host='uc.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0864aa00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uc.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e088b10a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uc.pt,"HTTPSConnectionPool(host='uc.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e083affd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uc.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e085f53d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uca.edu.ni,"HTTPSConnectionPool(host='uca.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0881ff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uca.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08136130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucatolica.edu.co,"HTTPSConnectionPool(host='ucatolica.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e093cbeb0>, 'Connection to ucatolica.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ucatolica.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08088130>, 'Connection to ucatolica.edu.co timed out. (connect timeout=2)'))"
ucc.ie,"HTTPSConnectionPool(host='ucc.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0894f2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucc.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08863910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucd.ie,"HTTPSConnectionPool(host='ucd.ie', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e084fdb20>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucd.ie', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08741ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uciteljska.net,"HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uciteljska.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
ucla.edu.ve,"HTTPSConnectionPool(host='ucla.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08535520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucla.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e087bc880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucol.mx,"HTTPSConnectionPool(host='ucol.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08b3e7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucol.mx', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08630e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucuenca.edu.ec,"HTTPSConnectionPool(host='ucuenca.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e080cf160>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucuenca.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e093d5700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ucv.ro,"HTTPSConnectionPool(host='ucv.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e083e5d90>, 'Connection to ucv.ro timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ucv.ro', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e08630820>, 'Connection to ucv.ro timed out. (connect timeout=2)'))"
ucv.ve,"HTTPSConnectionPool(host='ucv.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08b24bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ucv.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08650370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
udape.gob.bo,"HTTPSConnectionPool(host='udape.gob.bo', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.udape.gob.bo', port=443): Read timed out. (read timeout=2)"
udb.edu.sv,"HTTPSConnectionPool(host='udb.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0825a550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='udb.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e088c5910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
udg.mx,"HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='udg.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
udgtv.com,"HTTPSConnectionPool(host='udgtv.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='udgtv.com', port=80): Read timed out. (read timeout=2)"
udiconcalabria.org,"HTTPSConnectionPool(host='www.udiconcalabria.org', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.udiconcalabria.org', port=443): Read timed out. (read timeout=2)"
udp.cl,"HTTPSConnectionPool(host='udp.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e08a69910>, 'Connection to udp.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='udp.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e086e87c0>, 'Connection to udp.cl timed out. (connect timeout=2)'))"
udv.edu.gt,"HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='udv.edu.gt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uece.br,"HTTPSConnectionPool(host='uece.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e08b05e50>, 'Connection to uece.br timed out. (connect timeout=2)'))",Exceeded 30 redirects.
uem.br,"HTTPSConnectionPool(host='uem.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e081ed9a0>: Failed to establish a new connection: [Errno 113] No route to host'))","HTTPConnectionPool(host='uem.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0890ae20>: Failed to establish a new connection: [Errno 113] No route to host'))"
uerj.br,"HTTPSConnectionPool(host='uerj.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e06039d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uerj.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0632dbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ues.edu.sv,"HTTPSConnectionPool(host='ues.edu.sv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e060cde50>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ues.edu.sv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e083773d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
uesiglo21.edu.ar,"HTTPSConnectionPool(host='uesiglo21.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e06111760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uesiglo21.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08135700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uespi.br,"HTTPSConnectionPool(host='uespi.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e061a9d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uespi.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e06085e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ufam.edu.br,"HTTPSConnectionPool(host='ufam.edu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e06222400>, 'Connection to ufam.edu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufam.edu.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08094fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
ufma.br,"HTTPSConnectionPool(host='ufma.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e083982b0>, 'Connection to ufma.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufma.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e084d2d90>, 'Connection to ufma.br timed out. (connect timeout=2)'))"
ufmt.br,"HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ufmt.br', port=443): Read timed out. (read timeout=2)"
ufp.pt,"HTTPSConnectionPool(host='ufp.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e061c3d00>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ufp.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08b7bc70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
ufpe.br,"HTTPSConnectionPool(host='ufpe.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0839ed00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ufpe.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08682af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ufrj.br,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
ufs.ac.za,"HTTPSConnectionPool(host='ufs.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e06333550>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufs.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e0831ab80>, 'Connection to ufs.ac.za timed out. (connect timeout=2)'))"
ufu.br,"HTTPSConnectionPool(host='ufu.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2e0805a580>, 'Connection to ufu.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='ufu.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2e081189a0>, 'Connection to ufu.br timed out. (connect timeout=2)'))"
ug.edu.ec,"HTTPSConnectionPool(host='ug.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e087cfdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='ug.edu.ec', port=80): Read timed out. (read timeout=2)"
ugto.mx,"HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='ugto.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uhaena.com,"HTTPSConnectionPool(host='uhaena.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e0870a490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uhaena.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e0785d790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ui.ac.id,"HTTPSConnectionPool(host='ui.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ui.ac.id', port=443): Read timed out. (read timeout=2)"
uinsgd.ac.id,"HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uinsgd.ac.id', port=443): Read timed out. (read timeout=2)"
uji.es,"HTTPSConnectionPool(host='uji.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2e08386ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='uji.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e08834100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
uky.edu,"HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))","HTTPSConnectionPool(host='uky.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uky.edu' doesn't match 'www.uky.edu'"")))"
