ulapland.fi,"HTTPSConnectionPool(host='ulapland.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'ulapland.fi' doesn't match either of 'ww2.redu.fi', 'www.ww2.redu.fi'"")))","HTTPSConnectionPool(host='www.ulapland.fi', port=443): Read timed out. (read timeout=2)"
ulusiada.pt,"HTTPSConnectionPool(host='ulusiada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50b0f670>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='ulusiada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50ce71c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
um5.ac.ma,"HTTPSConnectionPool(host='um5.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50ac40d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='um5.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b1bc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uma.es,"HTTPSConnectionPool(host='uma.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50b0f130>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uma.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b1b3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umfcd.ro,"HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)"
umich.mx,"HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uminho.pt,"HTTPSConnectionPool(host='uminho.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50c75ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uminho.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50adc370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
umitcelik.net,"HTTPSConnectionPool(host='umitcelik.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509dfe50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='umitcelik.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50ce77f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
ums.ac.id,"HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
umss.edu.bo,"HTTPSConnectionPool(host='umss.edu.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'umss.edu.bo' doesn't match 'www.umss.edu.bo'"")))","HTTPSConnectionPool(host='umss.edu.bo', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50b292b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unach.edu.ec,"HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unad.edu.co,"HTTPSConnectionPool(host='unad.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50968d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unad.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509af280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unan.edu.ni,"HTTPSConnectionPool(host='unan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509b9910>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b0fa60>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unand.ac.id,"HTTPSConnectionPool(host='unand.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unand.ac.id', port=443): Read timed out. (read timeout=2)"
uncoma.edu.ar,"HTTPSConnectionPool(host='uncoma.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509d1100>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uncoma.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509df9d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uncu.edu.ar,"HTTPSConnectionPool(host='uncu.edu.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uncuyo.edu.ar', port=443): Read timed out. (read timeout=2)"
uned.es,"HTTPSConnectionPool(host='uned.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50a55700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uned.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b1bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unemi.edu.ec,"HTTPSConnectionPool(host='unemi.edu.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac5092cb80>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unemi.edu.ec', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac509ed820>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))"
uni-lj.si,"HTTPSConnectionPool(host='uni-lj.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac5092ca00>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uni-lj.si', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac50909c10>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))"
uni-muenchen.de,"HTTPSConnectionPool(host='uni-muenchen.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac5092c0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-muenchen.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b1b430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-regensburg.de,"HTTPSConnectionPool(host='uni-regensburg.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50ad0340>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uni-regensburg.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5093a8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uni-sofia.bg,"HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)"
uni-vt.bg,"HTTPSConnectionPool(host='uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uni.wroc.pl,"HTTPSConnectionPool(host='uni.wroc.pl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uni.wroc.pl', port=443): Read timed out. (read timeout=2)"
unibg.it,"HTTPSConnectionPool(host='unibg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac507442b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unibg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50775040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unicamp.br,"HTTPSConnectionPool(host='unicamp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50aac0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unicamp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50b1be80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unican.es,"HTTPSConnectionPool(host='unican.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50cb9760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unican.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5092c430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniceub.br,"HTTPSConnectionPool(host='uniceub.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'uniceub.br' doesn't match either of '*.ceub.br', 'ceub.br', '*.uniceub.br', 'cepublic.emailmkt.uniceub.br', 'eaplay.api.uniceub.br', 'eventos.api.uniceub.br', 'www.biblioteca.uniceub.br', 'www.bibliotecaweb.uniceub.br', 'www.campusonline1.ead.uniceub.br', 'www.campusonline2.ead.uniceub.br', 'www.ea.uniceub.br', 'www.ep.uniceub.br', 'www.espacoaluno.uniceub.br', 'www.saude.uniceub.br', 'www.sgi.uniceub.br', 'servicos.gds.uniceub.br', 'cepublic.emailmkt.ceub.br', 'eaplay.api.ceub.br', 'eventos.api.ceub.br', 'www.biblioteca.ceub.br', 'www.bibliotecaweb.ceub.br', 'www.campusonline1.ead.ceub.br', 'www.campusonline2.ead.ceub.br', 'www.ea.ceub.br', 'www.ep.ceub.br', 'www.espacoaluno.ceub.br', 'www.saude.ceub.br', 'www.sgi.ceub.br', 'servicos.gds.ceub.br', 'apolo.uniceub.br', 'bi.uniceub.br', 'mobilidade.uniceub.br', 'pbi.uniceub.br', 'radiusan.uniceub.br', 'radiustg.uniceub.br', 'stinger.uniceub.br', 'wifian.uniceub.br', 'wifitg.uniceub.br', 'apolo.ceub.br', 'bi.ceub.br', 'mobilidade.ceub.br', 'pbi.ceub.br', 'radiusan.ceub.br', 'radiustg.ceub.br', 'stinger.ceub.br', 'wifian.ceub.br', 'wifitg.ceub.br'"")))","HTTPSConnectionPool(host='www.uniceub.br', port=443): Read timed out. (read timeout=2)"
unifap.br,"HTTPSConnectionPool(host='unifap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506d3e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='unifap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac507e9fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
unika.ac.id,"HTTPConnectionPool(host='www.unika.ac.id', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unika.ac.id', port=80): Read timed out. (read timeout=2)"
unikom.ac.id,"HTTPSConnectionPool(host='unikom.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unikom.ac.id', port=443): Read timed out. (read timeout=2)"
unimal.ac.id,"HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unimal.ac.id', port=443): Read timed out. (read timeout=2)"
unimet.edu.ve,"HTTPSConnectionPool(host='unimet.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac508241f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimet.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50607e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimib.it,"HTTPSConnectionPool(host='unimib.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50b299d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unimib.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50736790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unimilitar.edu.co,"HTTPSConnectionPool(host='unimilitar.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac508b8d90>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unimilitar.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac509686d0>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))"
uniminuto.edu,"HTTPSConnectionPool(host='uniminuto.edu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac509af730>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uniminuto.edu', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac5061e610>, 'Connection to uniminuto.edu timed out. (connect timeout=2)'))"
unin.hr,"HTTPSConnectionPool(host='unin.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unin.hr', port=443): Read timed out. (read timeout=2)"
unina.it,"HTTPSConnectionPool(host='unina.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506077c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unina.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5062feb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unios.hr,"HTTPSConnectionPool(host='unios.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50a55be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unios.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50736550>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipamplona.edu.co,"HTTPSConnectionPool(host='unipamplona.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50736610>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipamplona.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509b9880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unipiloto.edu.co,"HTTPSConnectionPool(host='unipiloto.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50968580>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unipiloto.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50781040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniqlo.com,"HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)"
unirio.br,"HTTPSConnectionPool(host='unirio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506e0cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50712f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unirioja.es,"HTTPSConnectionPool(host='unirioja.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac5075dbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unirioja.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac505bcf70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma2.it,"HTTPSConnectionPool(host='uniroma2.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50ad0310>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uniroma2.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50607250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uniroma3.it,"HTTPSConnectionPool(host='uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unis.edu.gt,"HTTPSConnectionPool(host='unis.edu.gt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unis.edu.gt', port=443): Read timed out. (read timeout=2)"
unisant.edu.mx,"HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)"
unisba.ac.id,"HTTPSConnectionPool(host='unisba.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50590f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unisba.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac505bcee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unisimon.edu.co,"HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unito.it,"HTTPSConnectionPool(host='unito.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac508d4a30>, 'Connection to unito.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unito.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac508d4f70>, 'Connection to unito.it timed out. (connect timeout=2)'))"
unium.cz,"HTTPSConnectionPool(host='unium.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1124)')))","HTTPConnectionPool(host='www.unium.cz', port=80): Read timed out. (read timeout=2)"
univ-msila.dz,"HTTPSConnectionPool(host='univ-msila.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50b03b80>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='univ-msila.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac507126a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
univ-setif2.dz,"HTTPSConnectionPool(host='univ-setif2.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506f5550>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univ-setif2.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50a5ffd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univ-tlemcen.dz,"HTTPSConnectionPool(host='univ-tlemcen.dz', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.univ-tlemcen.dz', port=443): Read timed out. (read timeout=2)"
univalle.edu.co,"HTTPSConnectionPool(host='univalle.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50614940>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univalle.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac506f5d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
univap.br,"HTTPSConnectionPool(host='univap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50aac760>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='univap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac504fd250>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
universiteitleiden.nl,"HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)"
univr.it,"HTTPSConnectionPool(host='univr.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac506072b0>, 'Connection to univr.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='univr.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac50614a60>, 'Connection to univr.it timed out. (connect timeout=2)'))"
unizd.hr,"HTTPSConnectionPool(host='unizd.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50775d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unizd.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509b9ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unj.ac.id,"HTTPSConnectionPool(host='unj.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1124)')))","HTTPConnectionPool(host='unj.ac.id', port=80): Read timed out. (read timeout=2)"
unja.ac.id,"HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)"
unl.edu.ec,"HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unl.pt,"HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unlpam.edu.ar,"HTTPSConnectionPool(host='unlpam.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50ce7700>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unlpam.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50945040>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unmuhjember.ac.id,"HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unne.edu.ar,"HTTPSConnectionPool(host='unne.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac507c2490>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='unne.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50570130>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unotices.com,"HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)"
unp.ac.id,"HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
unpar.ac.id,"HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out.","HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out."
unpatti.ac.id,"HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)"
unpret.ro,"HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)"
uns.ac.rs,"HTTPSConnectionPool(host='uns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506e09d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac507c2580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
unse.edu.ar,"HTTPSConnectionPool(host='unse.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50ac4670>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unse.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac508c44c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unsrat.ac.id,"HTTPSConnectionPool(host='unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uop.edu.jo,"HTTPSConnectionPool(host='uop.edu.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uop.edu.jo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
uop.gr,"HTTPSConnectionPool(host='uop.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509826a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uop.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509af220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
up.ac.za,"HTTPSConnectionPool(host='up.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac50570ac0>, 'Connection to up.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='up.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac5059c580>, 'Connection to up.ac.za timed out. (connect timeout=2)'))"
upatras.gr,"HTTPSConnectionPool(host='upatras.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50968ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upatras.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509c66a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
upb.ro,"HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)"
upc.hu,"HTTPSConnectionPool(host='www.upc.hu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.upc.hu', port=443): Read timed out. (read timeout=2)"
upcitemdb.com,"HTTPSConnectionPool(host='upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
upv.es,"HTTPSConnectionPool(host='upv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509b93d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='upv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50702ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uq.edu.au,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
uraccan.edu.ni,"HTTPSConnectionPool(host='uraccan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50db8a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uraccan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50982d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
urdu.co,"HTTPSConnectionPool(host='urdu.co', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='urdu.co', port=80): Read timed out. (read timeout=2)"
url.edu.gt,"HTTPSConnectionPool(host='url.edu.gt', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac506d35e0>, 'Connection to url.edu.gt timed out. (connect timeout=2)'))","HTTPConnectionPool(host='url.edu.gt', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac504fd670>, 'Connection to url.edu.gt timed out. (connect timeout=2)'))"
us.es,"HTTPSConnectionPool(host='us.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506d3d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='us.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac507c6b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usceshoppingcenter.rs,"HTTPSConnectionPool(host='usceshoppingcenter.rs', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usceshoppingcenter.rs', port=443): Read timed out. (read timeout=2)"
usembassy.gov,"HTTPSConnectionPool(host='www.usembassy.gov', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.usembassy.gov', port=443): Read timed out. (read timeout=2)"
usfx.bo,"HTTPSConnectionPool(host='usfx.bo', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usfx.bo', port=80): Read timed out. (read timeout=2)"
uskudar.edu.tr,"HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
usm.my,"HTTPSConnectionPool(host='usm.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac504fd610>, 'Connection to usm.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='usm.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac505c9f10>, 'Connection to usm.my timed out. (connect timeout=2)'))"
usmba.ac.ma,"HTTPSConnectionPool(host='usmba.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac506f5b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usmba.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac504df460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
usnews.com,"HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usnews.com', port=80): Read timed out. (read timeout=2)"
uson.mx,"HTTPSConnectionPool(host='uson.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac505bce20>, 'Connection to uson.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uson.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac50869e20>, 'Connection to uson.mx timed out. (connect timeout=2)'))"
usta.edu.co,"HTTPSConnectionPool(host='usta.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac507e9a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='usta.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50479700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uta.edu.ec,"HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)"
utalca.cl,"HTTPSConnectionPool(host='utalca.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac5059cc40>, 'Connection to utalca.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utalca.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac50607e50>, 'Connection to utalca.cl timed out. (connect timeout=2)'))"
utcluj.ro,"HTTPSConnectionPool(host='utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
utdanningsforskning.no,"HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)"
ute.com.uy,"HTTPSConnectionPool(host='ute.com.uy', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ute.com.uy', port=443): Read timed out. (read timeout=2)"
utl.pt,"HTTPSConnectionPool(host='utl.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509af2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utl.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50ad0460>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utlib.ee,"HTTPSConnectionPool(host='utlib.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fac50570640>, 'Connection to utlib.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utlib.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fac512504c0>, 'Connection to utlib.ee timed out. (connect timeout=2)'))"
utm.my,"HTTPSConnectionPool(host='www.utm.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.utm.my', port=443): Read timed out. (read timeout=2)"
utmachala.edu.ec,"HTTPSConnectionPool(host='utmachala.edu.ec', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50781520>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='utmachala.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac508c4520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
utn.edu.ec,"HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)"
uv.es,"HTTPSConnectionPool(host='uv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac5075c640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='uv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac503aeac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
uwa.edu.au,"HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)"
vaga.lt,"HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)"
valeta.bg,"HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)"
valledelcauca.gov.co,"HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
valmiera.lv,"HTTPSConnectionPool(host='valmiera.lv', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac507c61f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPSConnectionPool(host='www.valmierasnovads.lv', port=443): Read timed out. (read timeout=2)"
valoda.lv,"HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
vanemuine.ee,"HTTPSConnectionPool(host='www.vanemuine.ee', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vanemuine.ee', port=443): Read timed out. (read timeout=2)"
vantaa.fi,"HTTPSConnectionPool(host='vantaa.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))","HTTPSConnectionPool(host='www.vantaa.fi', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))"
vatican.va,"HTTPSConnectionPool(host='vatican.va', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac509d1d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5042a220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdi.lt,"HTTPSConnectionPool(host='vdi.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac508c47c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vdi.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac51250280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
vdu.lt,"HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)"
vec.go.th,"HTTPSConnectionPool(host='vec.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac5093a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vec.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac509b9610>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
veleposlanistvo.si,"HTTPSConnectionPool(host='veleposlanistvo.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac512a6ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='veleposlanistvo.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5014c400>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
velocidadmaxima.com,"HTTPSConnectionPool(host='velocidadmaxima.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='velocidadmaxima.com', port=443): Read timed out. (read timeout=2)"
verangola.net,"HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)"
vergelijken-chappers.be,"HTTPSConnectionPool(host='vergelijken-chappers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac50054b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vergelijken-chappers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac50a399d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verizon.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
verkkokirjasto.fi,"HTTPSConnectionPool(host='verkkokirjasto.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fac5020f7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='verkkokirjasto.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac508d4520>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
very.co.uk,"HTTPSConnectionPool(host='www.very.co.uk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.very.co.uk', port=443): Read timed out. (read timeout=2)"
veselebydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
vesti-online.com,"HTTPSConnectionPool(host='www.vesti-online.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vesti-online.com', port=443): Read timed out. (read timeout=2)"
vestnikstroitel.bg,"HTTPSConnectionPool(host='vestnikstroitel.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vestnikstroitel.bg', port=443): Read timed out. (read timeout=2)"
vfo.vn,"HTTPSConnectionPool(host='vfo.vn', port=443): Read timed out. (read timeout=2)","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
