ula.ve,"HTTPSConnectionPool(host='ula.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f552a700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='ula.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f53c6e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
ulapland.fi,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPSConnectionPool(host='www.ulapland.fi', port=443): Read timed out. (read timeout=2)"
ulaval.ca,"HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='ulaval.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
ultratop.be,"HTTPSConnectionPool(host='ultratop.be', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.ultratop.be', port=443): Read timed out. (read timeout=2)"
ulusiada.pt,"HTTPSConnectionPool(host='ulusiada.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f41b9df0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='ulusiada.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f51c7970>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
um5.ac.ma,"HTTPSConnectionPool(host='um5.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f39497f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='um5.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f513a8e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uma.es,"HTTPSConnectionPool(host='uma.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f3931df0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uma.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4d09670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
umanitoba.ca,"HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='umanitoba.ca', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
umfcd.ro,"HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='umfcd.ro', port=443): Read timed out. (read timeout=2)"
umich.mx,"HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='umich.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uminho.pt,"HTTPSConnectionPool(host='uminho.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f2cd34c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uminho.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f33f7340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
umm.ac.id,"HTTPSConnectionPool(host='umm.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.umm.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f293ed90>: Failed to establish a new connection: [Errno 113] No route to host'))"
umpo.ac.id,"HTTPSConnectionPool(host='umpo.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPSConnectionPool(host='umpo.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))"
ums.ac.id,"HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.ums.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
umsa.bo,"HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='umsa.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unach.edu.ec,"HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unach.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unad.edu.co,"HTTPSConnectionPool(host='unad.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f266a1f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unad.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2710580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unan.edu.ni,"HTTPSConnectionPool(host='unan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f2670490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f271abe0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uncoma.edu.ar,"HTTPSConnectionPool(host='uncoma.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f26e0340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uncoma.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2726ac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uned.es,"HTTPSConnectionPool(host='uned.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f56c52b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uned.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4438400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unemi.edu.ec,"HTTPSConnectionPool(host='unemi.edu.ec', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f266a580>, 'Connection to unemi.edu.ec timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unemi.edu.ec', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f259c820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unescwa.org,"HTTPSConnectionPool(host='unescwa.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f265fcd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unescwa.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f23e3940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uni-kiel.de,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","HTTPSConnectionPool(host='www.uni-kiel.de', port=443): Read timed out. (read timeout=2)"
uni-lj.si,"HTTPSConnectionPool(host='uni-lj.si', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f2b17130>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uni-lj.si', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f2b526d0>, 'Connection to uni-lj.si timed out. (connect timeout=2)'))"
uni-muenchen.de,"HTTPSConnectionPool(host='uni-muenchen.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4970fa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uni-muenchen.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f1d4bf40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uni-regensburg.de,"HTTPSConnectionPool(host='uni-regensburg.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4970e20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uni-regensburg.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2933880>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uni-sofia.bg,"HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uni-sofia.bg', port=443): Read timed out. (read timeout=2)"
uni-vt.bg,"HTTPSConnectionPool(host='uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.uni-vt.bg', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unibg.it,"HTTPSConnectionPool(host='unibg.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f47463d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unibg.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f1e62a60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unica.it,"HTTPSConnectionPool(host='unica.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f0f0bac0>, 'Connection to unica.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unica.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f1765e50>, 'Connection to unica.it timed out. (connect timeout=2)'))"
unicamp.br,"HTTPSConnectionPool(host='unicamp.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4a87490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unicamp.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4238b20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unican.es,"HTTPSConnectionPool(host='unican.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f2c66f10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unican.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4574a90>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unicartagena.edu.co,"HTTPSConnectionPool(host='unicartagena.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f1199070>, 'Connection to unicartagena.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unicartagena.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f3dc8f70>, 'Connection to unicartagena.edu.co timed out. (connect timeout=2)'))"
unicentro.br,"HTTPSConnectionPool(host='unicentro.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f3183f70>, 'Connection to unicentro.br timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unicentro.br', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f1289910>, 'Connection to unicentro.br timed out. (connect timeout=2)'))"
unifap.br,"HTTPSConnectionPool(host='unifap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f46f9c70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))","HTTPConnectionPool(host='unifap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2ddb190>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
unimal.ac.id,"HTTPSConnectionPool(host='unimal.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))","HTTPSConnectionPool(host='unimal.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))"
unimet.edu.ve,"HTTPSConnectionPool(host='unimet.edu.ve', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f37852b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unimet.edu.ve', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f17b49a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unimib.it,"HTTPSConnectionPool(host='unimib.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f09d1220>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unimib.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4083580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unimilitar.edu.co,"HTTPSConnectionPool(host='unimilitar.edu.co', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f3779820>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unimilitar.edu.co', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f4045e80>, 'Connection to unimilitar.edu.co timed out. (connect timeout=2)'))"
unin.hr,"HTTPSConnectionPool(host='unin.hr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.unin.hr', port=443): Read timed out. (read timeout=2)"
unina.it,"HTTPSConnectionPool(host='unina.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f380f490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unina.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f38d3cd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unionesarda.it,"HTTPSConnectionPool(host='unionesarda.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'unionesarda.it' doesn't match '*.unionesarda.it'"")))","HTTPSConnectionPool(host='www.unionesarda.it', port=443): Read timed out. (read timeout=2)"
unionjalisco.mx,"HTTPSConnectionPool(host='unionjalisco.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(""hostname 'unionjalisco.mx' doesn't match either of 'www.eluni.mx', 'eluni.mx', 'www.unionjalisco.mx', 'www.unionguanajuato.mx', 'www.unionyucatan.mx', 'www.union-morelos.mx', 'www.unionhidalgo.mx', 'www.unionqueretaro.mx', 'www.unionchiapas.mx', 'www.eluniversalqueretaro.mx', 'www.unioncancun.mx', 'dev.elgrafico.mx', 'www.unionedomex.mx', 'www.unionpuebla.mx', 'www.unioncdmx.mx'"")))","HTTPSConnectionPool(host='www.unionjalisco.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f30db7f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unios.hr,"HTTPSConnectionPool(host='unios.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f38ffbe0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unios.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f0671280>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unipamplona.edu.co,"HTTPSConnectionPool(host='unipamplona.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4b8bfa0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unipamplona.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f3364b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unipiloto.edu.co,"HTTPSConnectionPool(host='unipiloto.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4b8b3d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unipiloto.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f03d5d00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uniqlo.com,"HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uniqlo.com', port=443): Read timed out. (read timeout=2)"
unirio.br,"HTTPSConnectionPool(host='unirio.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f3912c40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unirio.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f04b8490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unirioja.es,"HTTPSConnectionPool(host='unirioja.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f1e80760>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unirioja.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f0ef0400>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uniroma2.it,"HTTPSConnectionPool(host='uniroma2.it', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f36b2940>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uniroma2.it', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f16d3070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uniroma3.it,"HTTPSConnectionPool(host='uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.uniroma3.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unisa.ac.za,"HTTPSConnectionPool(host='unisa.ac.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.unisa.ac.za', port=443): Max retries exceeded with url: /sites/corporate/default (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1131)')))"
unisant.edu.mx,"HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unisant.edu.mx', port=443): Read timed out. (read timeout=2)"
unisba.ac.id,"HTTPSConnectionPool(host='unisba.ac.id', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f53963d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unisba.ac.id', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f03618b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unisimon.edu.co,"HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unisimon.edu.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unito.it,"HTTPSConnectionPool(host='unito.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f0671400>, 'Connection to unito.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='unito.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8eff65f40>, 'Connection to unito.it timed out. (connect timeout=2)'))"
unium.cz,"HTTPSConnectionPool(host='unium.cz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1131)')))","HTTPConnectionPool(host='unium.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f1765f10>, 'Connection to unium.cz timed out. (connect timeout=2)'))"
univ-msila.dz,"HTTPSConnectionPool(host='univ-msila.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f401f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='univ-msila.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f3e52820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
univ-setif2.dz,"HTTPSConnectionPool(host='univ-setif2.dz', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f17b4af0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='univ-setif2.dz', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8efcc4fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
univ-tlemcen.dz,"HTTPSConnectionPool(host='univ-tlemcen.dz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.univ-tlemcen.dz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
univalle.edu.co,"HTTPSConnectionPool(host='univalle.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4364040>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='univalle.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8efc84340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
univap.br,"HTTPSConnectionPool(host='univap.br', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4320c40>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='univap.br', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f42056a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
universiteitleiden.nl,"HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.universiteitleiden.nl', port=443): Read timed out. (read timeout=2)"
univr.it,"HTTPSConnectionPool(host='univr.it', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f2f90940>, 'Connection to univr.it timed out. (connect timeout=2)'))","HTTPConnectionPool(host='univr.it', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f0efcf10>, 'Connection to univr.it timed out. (connect timeout=2)'))"
unizd.hr,"HTTPSConnectionPool(host='unizd.hr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f1a61340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unizd.hr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eef24490>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unj.ac.id,"HTTPSConnectionPool(host='unj.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))","HTTPConnectionPool(host='unj.ac.id', port=80): Read timed out. (read timeout=2)"
unja.ac.id,"HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unja.ac.id', port=443): Read timed out. (read timeout=2)"
unl.edu.ec,"HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unl.edu.ec', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unl.pt,"HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unl.pt', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unlpam.edu.ar,"HTTPSConnectionPool(host='unlpam.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8eea89f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unlpam.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eefeaca0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unmuhjember.ac.id,"HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unmuhjember.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unne.edu.ar,"HTTPSConnectionPool(host='unne.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4ca8550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unne.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8ef0c34c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unodc.org,"HTTPSConnectionPool(host='unodc.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f1d40100>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='unodc.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4b05c70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unotices.com,"HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='unotices.com', port=443): Read timed out. (read timeout=2)"
unp.ac.id,"HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='unp.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
unpar.ac.id,"HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out.","HTTPSConnectionPool(host='unpar.ac.id', port=443): Read timed out."
unpatti.ac.id,"HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.unpatti.ac.id', port=443): Read timed out. (read timeout=2)"
unpret.ro,"HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.unpret.ro', port=80): Read timed out. (read timeout=2)"
uns.ac.rs,"HTTPSConnectionPool(host='uns.ac.rs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f30a8550>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uns.ac.rs', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f4e695b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
unse.edu.ar,"HTTPSConnectionPool(host='unse.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8efccddf0>: Failed to establish a new connection: [Errno 111] Connection refused'))","HTTPConnectionPool(host='unse.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2b52700>: Failed to establish a new connection: [Errno 111] Connection refused'))"
unsrat.ac.id,"HTTPSConnectionPool(host='unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.unsrat.ac.id', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uob.edu.bh,"HTTPSConnectionPool(host='uob.edu.bh', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f494bc10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uob.edu.bh', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8efc84520>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uop.gr,"HTTPSConnectionPool(host='uop.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f416ed30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uop.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f1a6d2b0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
up.ac.za,"HTTPSConnectionPool(host='up.ac.za', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f42de220>, 'Connection to up.ac.za timed out. (connect timeout=2)'))","HTTPConnectionPool(host='up.ac.za', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8efd10850>, 'Connection to up.ac.za timed out. (connect timeout=2)'))"
upatras.gr,"HTTPSConnectionPool(host='upatras.gr', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f467d7f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='upatras.gr', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f1741b80>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
upb.ro,"HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='upb.ro', port=443): Read timed out. (read timeout=2)"
upcitemdb.com,"HTTPSConnectionPool(host='upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.upcitemdb.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
uph.edu,"HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uph.edu', port=443): Read timed out. (read timeout=2)"
upv.es,"HTTPSConnectionPool(host='upv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8efce01f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='upv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eedbe3a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uq.edu.au,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
uraccan.edu.ni,"HTTPSConnectionPool(host='uraccan.edu.ni', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f0e88fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uraccan.edu.ni', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eef246d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uruguayconcursa.gub.uy,"HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))","HTTPSConnectionPool(host='uruguayconcursa.gub.uy', port=443): Max retries exceeded with url: // (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1131)')))"
us.es,"HTTPSConnectionPool(host='us.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8eebcc130>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='us.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8ee074100>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
usdwellhouse.com,"HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usdwellhouse.com', port=443): Read timed out. (read timeout=2)"
usfx.bo,"HTTPSConnectionPool(host='usfx.bo', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usfx.bo', port=80): Read timed out. (read timeout=2)"
uskudar.edu.tr,"HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='uskudar.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
usm.my,"HTTPSConnectionPool(host='usm.my', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f1a6da90>, 'Connection to usm.my timed out. (connect timeout=2)'))","HTTPConnectionPool(host='usm.my', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f04b8760>, 'Connection to usm.my timed out. (connect timeout=2)'))"
usmba.ac.ma,"HTTPSConnectionPool(host='usmba.ac.ma', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f2c0dac0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='usmba.ac.ma', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2f90580>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
usnews.com,"HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=2)","HTTPConnectionPool(host='usnews.com', port=80): Read timed out. (read timeout=2)"
uson.mx,"HTTPSConnectionPool(host='uson.mx', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f2cad130>, 'Connection to uson.mx timed out. (connect timeout=2)'))","HTTPConnectionPool(host='uson.mx', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f2ea2a60>, 'Connection to uson.mx timed out. (connect timeout=2)'))"
usta.edu.co,"HTTPSConnectionPool(host='usta.edu.co', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8eef04be0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='usta.edu.co', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eef9ae20>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
usv.ro,"HTTPSConnectionPool(host='usv.ro', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='usv.ro', port=443): Read timed out. (read timeout=2)"
uta.edu.ec,"HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='uta.edu.ec', port=443): Read timed out. (read timeout=2)"
utad.pt,"HTTPSConnectionPool(host='www.utad.pt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.utad.pt', port=443): Read timed out. (read timeout=2)"
utalca.cl,"HTTPSConnectionPool(host='utalca.cl', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f4635d00>, 'Connection to utalca.cl timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utalca.cl', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8eed396d0>, 'Connection to utalca.cl timed out. (connect timeout=2)'))"
utcluj.ro,"HTTPSConnectionPool(host='utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.utcluj.ro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
utdanningsforskning.no,"HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='utdanningsforskning.no', port=443): Read timed out. (read timeout=2)"
utl.pt,"HTTPSConnectionPool(host='utl.pt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f310df10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='utl.pt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f306ba30>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
utlib.ee,"HTTPSConnectionPool(host='utlib.ee', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff8f42deaf0>, 'Connection to utlib.ee timed out. (connect timeout=2)'))","HTTPConnectionPool(host='utlib.ee', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ff8f38435e0>, 'Connection to utlib.ee timed out. (connect timeout=2)'))"
utn.edu.ec,"HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)","HTTPConnectionPool(host='www.utn.edu.ec', port=80): Read timed out. (read timeout=2)"
utusanborneo.com.my,"HTTPSConnectionPool(host='www.utusanborneo.com.my', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.utusanborneo.com.my', port=443): Read timed out. (read timeout=2)"
uv.es,"HTTPSConnectionPool(host='uv.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f303a070>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='uv.es', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f519a0a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
uwa.edu.au,"HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.uwa.edu.au', port=443): Read timed out. (read timeout=2)"
vacat.nl,"HTTPSConnectionPool(host='www.vacat.nl', port=443): Read timed out.","HTTPSConnectionPool(host='www.vacat.nl', port=443): Read timed out. (read timeout=2)"
vaga.lt,"HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='vaga.lt', port=443): Read timed out. (read timeout=2)"
valeta.bg,"HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='valeta.bg', port=443): Read timed out. (read timeout=2)"
valledelcauca.gov.co,"HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='www.valledelcauca.gov.co', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
valoda.lv,"HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))","HTTPSConnectionPool(host='valoda.lv', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"
vaneduc.edu.ar,"HTTPSConnectionPool(host='vaneduc.edu.ar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f2da57c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))","HTTPConnectionPool(host='vaneduc.edu.ar', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f2ac6250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"
varle.lt,"HTTPSConnectionPool(host='www.varle.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.varle.lt', port=443): Read timed out. (read timeout=2)"
vatican.va,"HTTPSConnectionPool(host='vatican.va', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f303a670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='vatican.va', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8edfbd730>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
vdi.lt,"HTTPSConnectionPool(host='vdi.lt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4f153a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='vdi.lt', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f478e460>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
vdu.lt,"HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.vdu.lt', port=443): Read timed out. (read timeout=2)"
ve.lt,"HTTPSConnectionPool(host='ve.lt', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='ve.lt', port=443): Read timed out. (read timeout=2)"
vec.go.th,"HTTPSConnectionPool(host='vec.go.th', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f4479be0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='vec.go.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8ecc19eb0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
veleposlanistvo.si,"HTTPSConnectionPool(host='veleposlanistvo.si', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8ec1055e0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='veleposlanistvo.si', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8eccc2f70>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
verangola.net,"HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.verangola.net', port=443): Read timed out. (read timeout=2)"
vergelijken-chappers.be,"HTTPSConnectionPool(host='vergelijken-chappers.be', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f15cd040>: Failed to establish a new connection: [Errno -2] Name or service not known'))","HTTPConnectionPool(host='vergelijken-chappers.be', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f0efcee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"
verizon.com,"('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))","('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))"
verkkokirjasto.fi,"HTTPSConnectionPool(host='verkkokirjasto.fi', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8f1289670>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))","HTTPConnectionPool(host='verkkokirjasto.fi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff8f30936a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))"
very.co.uk,"HTTPSConnectionPool(host='www.very.co.uk', port=443): Read timed out. (read timeout=2)","HTTPSConnectionPool(host='www.very.co.uk', port=443): Read timed out. (read timeout=2)"
veselebydleni.cz,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
